import assert from 'node:assert/strict';
import test from 'node:test';
import {createHash} from 'node:crypto';
import {academySetup,platformAction,configure,call,login,id,T,OTHER,ADMIN,ADMIN_AUTH,MANAGER,MANAGER_AUTH,EDITOR_AUTH,ACADEMY_INSTRUCTOR,ACADEMY_INSTRUCTOR_AUTH,SITE,COURSE,FOREIGN_COURSE,RUN,LEARNER_AUTH,STUDENT,seedPayment,seedEnrollment,HANDOFF,INVOICE,ACCOUNT,ENROLLMENT} from './fixtures/academy-platform-database.mjs';

const workspace=db=>call(db,'public.v1_academy_workspace_snapshot',{p_slug:'marktone'});
const permission=(db,key)=>call(db,'private_app.academy_has_permission_v1',{p_tenant_id:T,p_permission:key});
const learning=(db,role='manager')=>call(db,'public.v1_academy_training_snapshot',{p_slug:'marktone',p_role:role});
const tokenHash=createHash('sha256').update('test-opaque-academy-invitation').digest('hex');

test('academy entitlement, dedicated membership and role boundaries work without an Odeir membership',async t=>{
 const db=await academySetup();t.after(()=>db.close());
 assert.equal((await workspace(db)).enabled,false);
 await configure(db);
 for(const [email,role] of [['manager@example.test','manager'],['editor@example.test','website_editor'],['academy.instructor@example.test','instructor']])await platformAction(db,'set_member',{email,role,status:'active'});
 await login(db,MANAGER_AUTH);
 const view=await workspace(db);assert.equal(view.enabled,true);assert.equal(view.mode,'standalone');assert.equal(view.odeirAccess,false);
 assert.equal(view.permissions.manageLearning,true);assert.equal(view.permissions.verifyPayments,true);assert.equal(view.permissions.publishWebsite,true);
 assert.equal((await db.query('select count(*)::int n from access_control.memberships where subject_id=$1',[MANAGER])).rows[0].n,0);
 assert.equal(await call(db,'private_app.has_tenant_permission',{p_tenant_id:T,p_permission:'tenant.academy.write'}),false);
 assert.equal((await learning(db)).courses.length,1);
 assert.equal((await learning(db)).tenant.id,T);
 await assert.rejects(call(db,'public.v1_academy_training_action',{p_slug:'marktone',p_action:'save_draft',p_command_id:id(8300),p_payload:{courseId:FOREIGN_COURSE}}),/training_course_not_found/);
 await login(db,EDITOR_AUTH);assert.equal(await permission(db,'manageWebsite'),true);assert.equal(await permission(db,'publishWebsite'),false);
 await call(db,'private_app.cms_access_subject',{p_site_id:SITE,p_permission:'manage'});
 await assert.rejects(call(db,'private_app.cms_access_subject',{p_site_id:SITE,p_permission:'publish'}),/forbidden/);
 await assert.rejects(learning(db),/training_permission_denied/);
 await login(db,ACADEMY_INSTRUCTOR_AUTH);await assert.rejects(learning(db,'instructor'),/training_instructor_assignment_required/);
 await login(db,MANAGER_AUTH);
 await call(db,'public.v1_academy_training_action',{p_slug:'marktone',p_action:'assign_instructor',p_command_id:id(8301),p_payload:{runId:RUN,subjectId:ACADEMY_INSTRUCTOR}});
 await login(db,ACADEMY_INSTRUCTOR_AUTH);await learning(db,'instructor');
 assert.equal(await call(db,'private_app.training_is_instructor_v1',{p_tenant_id:T,p_run_id:RUN}),true);
 assert.equal(await call(db,'private_app.training_is_instructor_v1',{p_tenant_id:OTHER,p_run_id:RUN}),false);
 await db.query("update academy.platform_memberships set status='suspended' where subject_id=$1",[ACADEMY_INSTRUCTOR]);
 assert.equal(await call(db,'private_app.training_is_instructor_v1',{p_tenant_id:T,p_run_id:RUN}),false);
 await assert.rejects(learning(db,'instructor'),/training_instructor_assignment_required/);
 await login(db,MANAGER_AUTH);await db.query('update access_control.subjects set must_change_password=true where id=$1',[MANAGER]);
 await assert.rejects(workspace(db),/password_change_required/);assert.equal(await permission(db,'manageLearning'),false);
});

test('activation is explicit, bounded, versioned and idempotent; connected mode preserves financial authority',async t=>{
 const db=await academySetup();t.after(()=>db.close());
 await db.exec("select set_config('fixture.addon','no',false)");
 await assert.rejects(configure(db),/academy_subscription_required/);
 const expiresAt=(await db.query("select (now()+interval '1 day')::text v")).rows[0].v;
 const payload={expectedVersion:0,enabled:true,mode:'standalone',components:{lms:true,website:true,store:true},accessUntil:expiresAt,reason:'Explicit test pilot'};
 const result=await platformAction(db,'configure',payload,id(8400));assert.equal(result.after.version,1);
 assert.deepEqual(await platformAction(db,'configure',payload,id(8400)),result);
 await assert.rejects(platformAction(db,'configure',{...payload,mode:'connected'},id(8400)),/academy_command_conflict/);
 await assert.rejects(configure(db,{...payload}),/academy_config_conflict/);
 await assert.rejects(platformAction(db,'configure',payload,id(8401),'foreign'),/academy_pilot_only/);
 await platformAction(db,'set_member',{email:'manager@example.test',role:'manager',status:'active'});
 await login(db,MANAGER_AUTH);assert.equal((await workspace(db)).enabled,true);
 await login(db,ADMIN_AUTH);await configure(db,{...payload,expectedVersion:1,mode:'connected'});
 await login(db,MANAGER_AUTH);assert.equal(await permission(db,'manageLearning'),true);assert.equal(await permission(db,'verifyPayments'),false);assert.equal(await permission(db,'manageAdmissions'),false);
 await db.exec("update academy.platform_settings set access_until=now()-interval '1 second'");
 assert.equal((await workspace(db)).enabled,false);await assert.rejects(learning(db),/academy_not_available/);
});

test('academy invitation is bound to verified email and creates no staff account or cross-tenant grant',async t=>{
 const db=await academySetup();t.after(()=>db.close());
 await configure(db);
 await platformAction(db,'issue_invitation',{email:'learner@example.test',role:'manager',tokenHash});
 await login(db,null);
 const preview=await call(db,'public.v1_academy_invitation_preview',{p_slug:'marktone',p_token_hash:tokenHash});assert.equal(preview.email,'learner@example.test');
 await assert.rejects(call(db,'public.v1_academy_invitation_preview',{p_slug:'foreign',p_token_hash:tokenHash}),/academy_invitation_invalid/);
 await login(db,MANAGER_AUTH);await assert.rejects(call(db,'public.v1_academy_membership_accept',{p_slug:'marktone',p_token_hash:tokenHash}),/academy_invitation_invalid/);
 await login(db,LEARNER_AUTH);await db.query('update auth.users set email_confirmed_at=null where id=$1',[LEARNER_AUTH]);
 await assert.rejects(call(db,'public.v1_academy_membership_accept',{p_slug:'marktone',p_token_hash:tokenHash}),/academy_invitation_invalid/);
 await db.query('update auth.users set email_confirmed_at=now() where id=$1',[LEARNER_AUTH]);
 assert.equal((await call(db,'public.v1_academy_membership_accept',{p_slug:'marktone',p_token_hash:tokenHash})).role,'manager');
 assert.equal((await workspace(db)).odeirAccess,false);
 assert.equal((await call(db,'public.v1_academy_membership_accept',{p_slug:'marktone',p_token_hash:tokenHash})).role,'manager');
 await db.query("update academy.platform_memberships set status='suspended' where subject_id=(select id from access_control.subjects where auth_user_id=$1)",[LEARNER_AUTH]);
 await assert.rejects(call(db,'public.v1_academy_membership_accept',{p_slug:'marktone',p_token_hash:tokenHash}),/academy_invitation_invalid/);
 await db.exec('set role authenticated');
 await assert.rejects(db.query('select * from academy.platform_memberships'),/permission denied/);
 await db.exec('reset role');
 await login(db,ADMIN_AUTH);
 await platformAction(db,'issue_invitation',{email:'manager@example.test',role:'manager',tokenHash:createHash('sha256').update('older-role-token').digest('hex')});
 await platformAction(db,'set_member',{email:'manager@example.test',role:'website_editor',status:'active'});
 await login(db,MANAGER_AUTH);
 await assert.rejects(call(db,'public.v1_academy_membership_accept',{p_slug:'marktone',p_token_hash:createHash('sha256').update('older-role-token').digest('hex')}),/academy_invitation_invalid/);
});

test('standalone trial reaches genuine learner completion and certificate without Odeir subscription or journey activation',async t=>{
 const db=await academySetup();t.after(()=>db.close());
 await db.exec("select set_config('fixture.addon','no',false)");
 const accessUntil=(await db.query("select (now()+interval '1 day')::text v")).rows[0].v;
 await configure(db,{accessUntil,reason:'Explicit independent trial'});
 await platformAction(db,'set_member',{email:'manager@example.test',role:'manager',status:'active'});
 await db.query("insert into academy.training_financial_links(tenant_id,handoff_id,invoice_id,payer_account_id,policy,created_by_subject_id) values($1,$2,$3,$4,'full',$5)",[T,HANDOFF,INVOICE,ACCOUNT,ADMIN]);
 await seedPayment(db);await seedEnrollment(db);
 assert.equal((await db.query('select count(*)::int n from academy.training_journey_settings')).rows[0].n,0);
 await login(db,MANAGER_AUTH);
 let command=8500;
 const action=(action,payload)=>call(db,'public.v1_academy_training_action',{p_slug:'marktone',p_action:action,p_command_id:id(command++),p_payload:payload});
 const {versionId}=await action('save_draft',{courseId:COURSE,title:'Standalone real course',learningMode:'self_paced',policy:{minAttendancePercent:75,minAssessmentPercent:70,requireCompletedRun:false,certificateEnabled:true,termsVersion:'2026-09',supportEmail:'support@example.test'},units:[{title:'First lesson',kind:'text',body:'Verified learning material'},{title:'Assessment',kind:'quiz',maxAttempts:2,questions:[{id:'q1',prompt:'Choose the correct response',options:['Wrong','Correct'],correctOptionIndex:1}]}]});
 await action('publish_version',{versionId,humanReviewed:true});await action('assign_version',{versionId,enrollmentId:ENROLLMENT});
 await action('issue_invitation',{studentId:STUDENT,email:'learner@example.test',tokenHash});
 await db.exec("select set_config('fixture.jwt_role','service_role',false)");
 await assert.rejects(call(db,'public.v1_training_invitation_activation',{p_token_hash:tokenHash,p_claim_id:id(8590)}),/training_invitation_invalid/);
 await db.exec("select set_config('fixture.jwt_role','authenticated',false)");
 await login(db,null);assert.equal((await call(db,'public.v1_academy_learning_invitation_preview',{p_slug:'marktone',p_token_hash:tokenHash})).email,'learner@example.test');
 await login(db,LEARNER_AUTH);await action('accept_invitation',{tokenHash});
 const learner=await learning(db,'learner');assert.equal(learner.enrollments[0].financialAccess.trainingAllowed,true);
 const units=(await db.query('select id from academy.training_units where version_id=$1 order by position',[versionId])).rows;
 await action('open_unit',{enrollmentId:ENROLLMENT,unitId:units[0].id});await action('complete_unit',{enrollmentId:ENROLLMENT,unitId:units[0].id});
 await action('open_unit',{enrollmentId:ENROLLMENT,unitId:units[1].id});await action('submit_quiz',{enrollmentId:ENROLLMENT,unitId:units[1].id,answers:{q1:1}});
 await login(db,MANAGER_AUTH);const certificate=await action('issue_certificate',{enrollmentId:ENROLLMENT});assert.ok(certificate.certificateId);
 assert.equal((await db.query('select count(*)::int n from academy.certificates')).rows[0].n,1);
 assert.equal((await db.query('select count(*)::int n from access_control.memberships where subject_id=$1',[MANAGER])).rows[0].n,0);
});

test('standalone requests defer/resume/transfer/withdraw preserve learning history and reuse canonical money',async t=>{
 const db=await academySetup({governance:true});t.after(()=>db.close());
 await configure(db);await platformAction(db,'set_member',{email:'manager@example.test',role:'manager',status:'active'});
 await db.query("insert into academy.training_financial_links(tenant_id,handoff_id,invoice_id,payer_account_id,policy,created_by_subject_id) values($1,$2,$3,$4,'full',$5)",[T,HANDOFF,INVOICE,ACCOUNT,ADMIN]);
 await seedPayment(db);await seedEnrollment(db);
 await db.query("update academy.courses set program_kind='short_course' where id=$1",[COURSE]);
 await db.query('insert into academy.admission_governance_settings(tenant_id,enabled) values($1,true)',[T]);
 // A prior journey configuration must not force standalone managers into staff roles.
 await db.query('insert into academy.training_journey_settings(tenant_id,enabled) values($1,true)',[T]);
 await login(db,MANAGER_AUTH);
 let command=8600;
 const request=(action,payload,commandId=id(command++))=>call(db,'public.v1_academy_request_action',{p_slug:'marktone',p_action:action,p_command_id:commandId,p_payload:payload});
 const learningAction=(action,payload)=>call(db,'public.v1_academy_training_action',{p_slug:'marktone',p_action:action,p_command_id:id(command++),p_payload:payload});
 const version=await learningAction('save_draft',{courseId:COURSE,title:'Version pinned before transfer',learningMode:'self_paced',policy:{minAttendancePercent:75,minAssessmentPercent:70,requireCompletedRun:false,certificateEnabled:true,termsVersion:'2026-09',supportEmail:'support@example.test'},units:[{title:'Completed lesson',kind:'text',body:'Original educational evidence'},{title:'Final assessment',kind:'quiz',questions:[{id:'final',prompt:'Choose a response',options:['First','Second'],correctOptionIndex:0}]}]});
 await learningAction('publish_version',{versionId:version.versionId,humanReviewed:true});
 await learningAction('assign_version',{versionId:version.versionId,enrollmentId:ENROLLMENT});
 await learningAction('issue_invitation',{studentId:STUDENT,email:'learner@example.test',tokenHash});
 await login(db,LEARNER_AUTH);await learningAction('accept_invitation',{tokenHash});
 const unit=(await db.query('select id from academy.training_units where version_id=$1 order by position',[version.versionId])).rows[0].id;
 await learningAction('open_unit',{enrollmentId:ENROLLMENT,unitId:unit});await learningAction('complete_unit',{enrollmentId:ENROLLMENT,unitId:unit});
 await login(db,MANAGER_AUTH);
 let response=await request('create_request',{enrollmentId:ENROLLMENT,kind:'defer',reason:'Learner postponement'});
 await request('decide_request',{requestId:response.requestId,decision:'approve',reason:'Reviewed postponement'});
 assert.equal((await db.query('select metadata from academy.enrollments where id=$1',[ENROLLMENT])).rows[0].metadata.trainingJourneyDeferred,true);
 response=await request('create_request',{enrollmentId:ENROLLMENT,kind:'resume',reason:'Ready to resume'});
 await request('decide_request',{requestId:response.requestId,decision:'approve',reason:'Financial evidence verified'});
 assert.equal((await db.query('select metadata from academy.enrollments where id=$1',[ENROLLMENT])).rows[0].metadata.trainingJourneyDeferred,false);
 const targetRun=id(8690);
 await db.query("insert into academy.course_runs(id,tenant_id,course_id,run_code,title,delivery_mode,status,capacity) values($1,$2,$3,'TRANSFER-RUN','Another cohort','hybrid','open',1)",[targetRun,T,COURSE]);
 response=await request('create_request',{enrollmentId:ENROLLMENT,kind:'transfer',targetRunId:targetRun,reason:'Change cohort schedule'});
 const transfer=await request('decide_request',{requestId:response.requestId,decision:'approve',reason:'Same program and available seat'},id(8691));
 assert.ok(transfer.newEnrollmentId);
 assert.deepEqual(await request('decide_request',{requestId:response.requestId,decision:'approve',reason:'Same program and available seat'},id(8691)),transfer);
 assert.equal((await db.query('select status from academy.enrollments where id=$1',[ENROLLMENT])).rows[0].status,'withdrawn');
 assert.equal((await db.query('select count(*)::int n from accounting_core.payments')).rows[0].n,1);
 assert.equal((await db.query('select count(*)::int n from accounting_core.sales_documents')).rows[0].n,1);
 assert.equal((await db.query('select invoice_id from academy.training_financial_links where handoff_id=(select handoff_id from academy.enrollments where id=$1)',[transfer.newEnrollmentId])).rows[0].invoice_id,INVOICE);
 assert.equal((await db.query('select version_id from academy.training_enrollment_versions where enrollment_id=$1',[transfer.newEnrollmentId])).rows[0].version_id,version.versionId);
 assert.equal((await db.query('select count(*)::int n from academy.training_unit_progress where enrollment_id in ($1,$2) and unit_id=$3 and completed_at is not null',[ENROLLMENT,transfer.newEnrollmentId,unit])).rows[0].n,2);
 response=await request('create_request',{enrollmentId:transfer.newEnrollmentId,kind:'withdraw',reason:'Learner withdrawal request'});
 const withdrawal=await request('decide_request',{requestId:response.requestId,decision:'approve',reason:'Approved pending financial review'});
 assert.equal(withdrawal.refundProcessed,false);assert.equal(withdrawal.financialSettlementRequired,true);
 assert.equal((await db.query('select count(*)::int n from accounting_core.refunds')).rows[0].n,0);
 assert.equal((await db.query('select count(*)::int n from work_core.tasks')).rows[0].n,0);
 assert.equal((await call(db,'public.v1_academy_request_snapshot',{p_slug:'marktone'})).requests.length,4);
 await login(db,EDITOR_AUTH);await assert.rejects(call(db,'public.v1_academy_request_snapshot',{p_slug:'marktone'}),/training_permission_denied/);
});
