import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import ts from 'typescript';
import {JSDOM} from 'jsdom';
import React,{act} from 'react';
const require=createRequire(import.meta.url);
const code=ts.transpileModule(readFileSync(new URL('../components/team-directory.js',import.meta.url),'utf8'),{fileName:'team.jsx',compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;
const mod={exports:{}};
new Function('require','module','exports',code)(name=>name==='next/navigation'?{useRouter:()=>({refresh(){}})}:require(name),mod,mod.exports);
const Team=mod.exports.default;
const staff={id:'00000000-0000-4000-8000-000000000020',name:'Test employee',email:'staff@example.test',roleKey:'sales_user',accountStatus:'invited',status:'active'};

test('staff account dialog validates confirmation, keeps failed activation retryable, and clears password after success',async t=>{
 const dom=new JSDOM('<div id="root"></div>',{url:'https://odeir.test',pretendToBeVisual:true});
 const keys=['window','document','HTMLElement','FormData','fetch','IS_REACT_ACT_ENVIRONMENT'];const saved=Object.fromEntries(keys.map(k=>[k,globalThis[k]]));
 Object.assign(globalThis,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,FormData:dom.window.FormData,IS_REACT_ACT_ENVIRONMENT:true});
 const {createRoot}=await import('react-dom/client');const root=createRoot(document.getElementById('root'));
 t.after(async()=>{await act(async()=>root.unmount());dom.window.close();for(const k of keys){if(saved[k]===undefined)delete globalThis[k];else globalThis[k]=saved[k];}});
 const props={slug:'existing',initialData:{employees:[staff],roles:[{key:'sales_user',nameAr:'مبيعات'}]},canManage:true,canInvite:true,canResetPasswords:true,viewerRoleKeys:['tenant_owner']};
 const requests=[];globalThis.fetch=async(url,init)=>{requests.push({url,body:JSON.parse(init.body)});return {ok:requests.length>1,json:async()=>requests.length>1?{data:{completed:true}}:{error:'وصلت المنشأة إلى الحد الأقصى لحسابات الموظفين'}};};
 const button=text=>[...document.querySelectorAll('button')].find(el=>el.textContent===text);
 await act(async()=>root.render(React.createElement(Team,props)));
 await act(async()=>button('تعيين كلمة مرور وتفعيل الحساب').click());
 assert.ok(document.querySelector('input[name="password"][type="password"]'));
 document.querySelector('input[name="password"]').value='Strong123456!';
 document.querySelector('input[name="confirm"]').value='wrong-confirm';
 const submit=()=>act(async()=>document.querySelector('form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true})));
 await submit();assert.equal(requests.length,0);assert.match(document.body.textContent,/كلمتا المرور غير متطابقتين/);
 document.querySelector('input[name="confirm"]').value='Strong123456!';
 await submit();assert.equal(requests.length,1);assert.match(document.body.textContent,/الحد الأقصى/);
 assert.ok(document.querySelector('[role="dialog"]'));
 await submit();assert.equal(requests.length,2);assert.equal(requests[1].url,'/api/tenant/create-staff-account');
 assert.deepEqual(requests[1].body,{p_tenant_slug:'existing',p_staff_id:staff.id,password:'Strong123456!'});
 assert.equal(document.querySelector('[role="dialog"]'),null);assert.ok(!document.body.innerHTML.includes('Strong123456!'));
 await act(async()=>root.render(React.createElement(Team,{...props,canResetPasswords:false})));
 assert.equal(button('تعيين كلمة مرور وتفعيل الحساب'),undefined);
});
