'use client';

import { useEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';

const AR_DAYS=['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'];
const MONTHS=['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'];
function isoLocal(date){const d=new Date(date);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)}
function tenantSlug(){const match=location.pathname.match(/^\/tenant\/([^/]+)/);return match?decodeURIComponent(match[1]):''}
async function requestApi(action,options={}){
  const slug=tenantSlug();const query=options.query||{};if(slug&&!query.tenantSlug)query.tenantSlug=slug;
  const qs=new URLSearchParams(Object.entries(query).filter(([,v])=>v!==null&&v!==undefined&&v!=='')).toString();
  const response=await fetch('/api/operations/'+action+(qs?'?'+qs:''),{credentials:'include',headers:{...(options.body instanceof FormData?{}:{'content-type':'application/json'}),...(options.headers||{})},method:options.method||'GET',body:options.body instanceof FormData?options.body:options.body?JSON.stringify({...options.body,tenantSlug:slug||null}):undefined});
  const payload=await response.json().catch(()=>({error:'استجابة غير صالحة'}));if(!response.ok)throw new Error(payload.error||'تعذر تنفيذ الطلب');return payload;
}
function startOfMonth(value){return new Date(value.getFullYear(),value.getMonth(),1)}
function endOfMonth(value){return new Date(value.getFullYear(),value.getMonth()+1,0,23,59,59)}
function calendarDays(value){const start=startOfMonth(value);const first=new Date(start);first.setDate(first.getDate()-first.getDay());return Array.from({length:42},(_,i)=>{const d=new Date(first);d.setDate(first.getDate()+i);return d})}
function sameDay(a,b){return new Date(a).toDateString()===new Date(b).toDateString()}
function timingLabel(task){return task.timing_state==='overdue'?'متأخرة':task.timing_state==='today'?'اليوم':task.timing_state==='late'?'اكتملت متأخرًا':task.status==='completed'?'اكتملت في الموعد':'قادمة'}
function NavButton({target,children,onClick}){return target?createPortal(<button type="button" className="operations-nav-button" onClick={onClick}>{children}</button>,target):null}

export default function OperationsRuntime(){
  const [nav,setNav]=useState(null);const [context,setContext]=useState(null);const [open,setOpen]=useState(false);const [view,setView]=useState('calendar');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
  const [month,setMonth]=useState(()=>new Date());const [scope,setScope]=useState('mine');const [tasks,setTasks]=useState([]);const [showTaskForm,setShowTaskForm]=useState(false);
  const [taskForm,setTaskForm]=useState(()=>({title:'',description:'',assignedTo:'',startsAt:isoLocal(new Date()),dueAt:isoLocal(new Date(Date.now()+86400000)),recurrenceType:'none',recurrenceInterval:1,recurrenceEndAt:''}));
  const [uploadResult,setUploadResult]=useState(null);const [teamForm,setTeamForm]=useState({name:'',memberIds:[]});const [distribution,setDistribution]=useState(()=>({batchId:'',teamId:'',method:'fair',dueAt:isoLocal(new Date(Date.now()+86400000))}));
  const permissions=context?.permissions||{};const user=context?.user||{};const members=context?.members||[];const teams=context?.teams||[];const batches=context?.batches||[];

  async function bootstrap(){try{setError('');const data=await requestApi('bootstrap');setContext(data)}catch(e){setError(e.message)}}
  async function loadCalendar(){try{setBusy(true);setError('');const data=await requestApi('calendar',{query:{from:startOfMonth(month).toISOString(),to:endOfMonth(month).toISOString(),scope}});setTasks(Array.isArray(data)?data:[])}catch(e){setError(e.message)}finally{setBusy(false)}}
  useEffect(()=>{let timer;const find=()=>{const target=document.querySelector('.side nav');if(target){setNav(target);bootstrap();requestApi('heartbeat',{method:'POST',body:{}}).catch(()=>{});timer=setInterval(()=>requestApi('heartbeat',{method:'POST',body:{}}).catch(()=>{}),60000)}else setTimeout(find,250)};find();return()=>clearInterval(timer)},[]);
  useEffect(()=>{if(open&&view==='calendar')loadCalendar()},[open,view,month,scope]);
  function show(next){setView(next);setOpen(true);setNotice('');setError('')}
  async function createTask(event){event.preventDefault();try{setBusy(true);await requestApi('task',{method:'POST',body:{...taskForm,assignedTo:taskForm.assignedTo||null,recurrenceEndAt:taskForm.recurrenceEndAt||null}});setNotice('تم إنشاء المهمة بنجاح');setShowTaskForm(false);setTaskForm({...taskForm,title:'',description:''});await loadCalendar()}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function completeTask(taskId){try{setBusy(true);await requestApi('complete',{method:'POST',body:{taskId}});await loadCalendar()}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function upload(event){event.preventDefault();const file=event.currentTarget.elements.file.files[0];if(!file)return;try{setBusy(true);const form=new FormData();form.append('file',file);form.append('tenantSlug',tenantSlug());const data=await requestApi('upload',{method:'POST',body:form});setUploadResult(data);setNotice('تم رفع الملف والتحقق من البيانات');await bootstrap()}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function saveTeam(event){event.preventDefault();try{setBusy(true);await requestApi('team',{method:'POST',body:{name:teamForm.name,memberIds:teamForm.memberIds}});setNotice('تم حفظ فريق المبيعات');setTeamForm({name:'',memberIds:[]});await bootstrap()}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function distribute(event){event.preventDefault();try{setBusy(true);const data=await requestApi('distribute',{method:'POST',body:distribution});setNotice('تم توزيع '+data.assigned_count+' عميل وإنشاء المهام');await bootstrap()}catch(e){setError(e.message)}finally{setBusy(false)}}
  const days=useMemo(()=>calendarDays(month),[month]);
  const grouped=useMemo(()=>days.map(day=>({day,tasks:tasks.filter(task=>sameDay(task.due_at,day))})),[days,tasks]);
  const agenda=useMemo(()=>[...tasks].sort((a,b)=>new Date(a.due_at)-new Date(b.due_at)),[tasks]);

  return <>
    <NavButton target={nav} onClick={()=>{location.href='/tenant/'+encodeURIComponent(tenantSlug())+'/calendar'}}><span aria-hidden="true">▦</span><span>تقويم المهام</span></NavButton>
    {permissions.import&&<NavButton target={nav} onClick={()=>show('import')}><span aria-hidden="true">⇧</span><span>استيراد العملاء</span></NavButton>}
    {permissions.distribute&&<NavButton target={nav} onClick={()=>show('distribution')}><span aria-hidden="true">⇄</span><span>توزيع العملاء</span></NavButton>}
    {open&&createPortal(<div className="operations-overlay" role="dialog" aria-modal="true">
      <button className="operations-backdrop" aria-label="إغلاق" onClick={()=>setOpen(false)}/>
      <section className="operations-workspace">
        <header className="operations-header"><div><small>MARKTONE OPERATIONS</small><h2>{view==='calendar'?'تقويم المهام':view==='import'?'استيراد بيانات العملاء':'إدارة وتوزيع العملاء'}</h2></div><button type="button" className="operations-close" onClick={()=>setOpen(false)}>×</button></header>
        <nav className="operations-tabs"><button className={view==='calendar'?'active':''} onClick={()=>setView('calendar')}>التقويم</button>{permissions.import&&<button className={view==='import'?'active':''} onClick={()=>setView('import')}>الاستيراد</button>}{permissions.distribute&&<button className={view==='distribution'?'active':''} onClick={()=>setView('distribution')}>التوزيع والفرق</button>}</nav>
        {error&&<div className="operations-message error">{error}</div>}{notice&&<div className="operations-message success">{notice}</div>}
        <div className="operations-body">
          {view==='calendar'&&<>
            <div className="calendar-toolbar"><div><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><button onClick={()=>setMonth(new Date())}>اليوم</button><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button></div><strong>{MONTHS[month.getMonth()]} {month.getFullYear()}</strong><div><select value={scope} onChange={e=>setScope(e.target.value)}><option value="mine">مهامي</option>{permissions.viewTeam&&<option value="team">مهام فريقي</option>}{user.role_code==='admin'&&<option value="all">كل المهام</option>}</select><button className="primary" onClick={()=>setShowTaskForm(!showTaskForm)}>+ مهمة جديدة</button></div></div>
            {showTaskForm&&<form className="operations-form task-create" onSubmit={createTask}><label>عنوان المهمة<input required value={taskForm.title} onChange={e=>setTaskForm({...taskForm,title:e.target.value})}/></label><label>المسند إليه<select value={taskForm.assignedTo} onChange={e=>setTaskForm({...taskForm,assignedTo:e.target.value})}><option value="">أنا</option>{permissions.viewTeam&&members.map(member=><option key={member.user_id} value={member.user_id}>{member.display_name||member.email}</option>)}</select></label><label>تبدأ في<input type="datetime-local" value={taskForm.startsAt} onChange={e=>setTaskForm({...taskForm,startsAt:e.target.value})}/></label><label>تنتهي في<input required type="datetime-local" value={taskForm.dueAt} onChange={e=>setTaskForm({...taskForm,dueAt:e.target.value})}/></label><label>التكرار<select value={taskForm.recurrenceType} onChange={e=>setTaskForm({...taskForm,recurrenceType:e.target.value})}><option value="none">بدون تكرار</option><option value="daily">يومي</option><option value="weekly">أسبوعي</option><option value="monthly">شهري</option></select></label>{taskForm.recurrenceType!=='none'&&<><label>كل<input type="number" min="1" max="52" value={taskForm.recurrenceInterval} onChange={e=>setTaskForm({...taskForm,recurrenceInterval:e.target.value})}/></label><label>نهاية التكرار<input required type="datetime-local" value={taskForm.recurrenceEndAt} onChange={e=>setTaskForm({...taskForm,recurrenceEndAt:e.target.value})}/></label></>}<label className="wide">التفاصيل<textarea value={taskForm.description} onChange={e=>setTaskForm({...taskForm,description:e.target.value})}/></label><footer><button type="button" onClick={()=>setShowTaskForm(false)}>إلغاء</button><button className="primary" disabled={busy}>حفظ المهمة</button></footer></form>}
            <div className="calendar-weekdays">{AR_DAYS.map(day=><span key={day}>{day}</span>)}</div>
            <div className="calendar-grid">{grouped.map(({day,tasks:dayTasks})=><article key={day.toISOString()} className={(day.getMonth()!==month.getMonth()?'muted ':'')+(sameDay(day,new Date())?'today':'')}><header><b>{day.getDate()}</b><span>{dayTasks.length||''}</span></header>{dayTasks.slice(0,4).map(task=><button key={task.id} className={'calendar-task '+task.timing_state} onClick={()=>task.status!=='completed'&&completeTask(task.id)} title={task.title}><strong>{task.title}</strong><small>{new Date(task.due_at).toLocaleTimeString('ar-SA',{hour:'2-digit',minute:'2-digit'})} · {timingLabel(task)}</small></button>)}{dayTasks.length>4&&<em>+{dayTasks.length-4} مهام</em>}</article>)}</div>
            <div className="calendar-agenda">{agenda.length?agenda.map(task=><article key={task.id} className={task.timing_state}><time>{new Date(task.due_at).toLocaleDateString('ar-SA',{weekday:'short',day:'numeric',month:'short'})}<b>{new Date(task.due_at).toLocaleTimeString('ar-SA',{hour:'2-digit',minute:'2-digit'})}</b></time><div><strong>{task.title}</strong><span>{task.assigned_name||''}{task.lead?.customer_name?' · '+task.lead.customer_name:''}</span></div><em>{timingLabel(task)}</em>{task.status!=='completed'&&<button onClick={()=>completeTask(task.id)}>إتمام</button>}</article>):<p className="empty-state">لا توجد مهام في هذه الفترة.</p>}</div>
          </>}
          {view==='import'&&permissions.import&&<div className="import-layout"><section className="operations-card intro-card"><span>01</span><h3>حمّل النموذج الموحد</h3><p>النموذج يحتوي على: الاسم، رقم الهاتف، البرنامج أو الدورة، واسم الإعلان.</p><a className="primary button-link" href={'/api/operations/template?tenantSlug='+encodeURIComponent(tenantSlug())}>تحميل نموذج Excel</a></section><section className="operations-card"><span>02</span><h3>ارفع بيانات العملاء</h3><form className="upload-form" onSubmit={upload}><label className="file-drop"><input name="file" type="file" accept=".xlsx,.xls,.csv" required/><b>اختر ملف Excel أو اسحبه هنا</b><small>حتى 10,000 صف في الملف الواحد</small></label><button className="primary" disabled={busy}>رفع وفحص البيانات</button></form>{uploadResult&&<div className="import-summary"><div><b>{uploadResult.total_rows}</b><span>إجمالي الصفوف</span></div><div><b>{uploadResult.valid_rows}</b><span>صالحة</span></div><div><b>{uploadResult.duplicate_rows}</b><span>مكررة</span></div><div><b>{uploadResult.invalid_rows}</b><span>غير مكتملة</span></div></div>}</section></div>}
          {view==='distribution'&&permissions.distribute&&<div className="distribution-layout"><section className="operations-card"><h3>فريق المبيعات</h3><p>أنشئ فريقًا وحدد أعضاؤه. مسؤول المبيعات الحالي يصبح مدير الفريق والمسؤول عن المهام المسندة.</p><form className="operations-form" onSubmit={saveTeam}><label className="wide">اسم الفريق<input required value={teamForm.name} onChange={e=>setTeamForm({...teamForm,name:e.target.value})} placeholder="مثال: فريق مبيعات البرامج المهنية"/></label><fieldset className="wide member-picker"><legend>أعضاء الفريق</legend>{members.filter(member=>['sales_agent','member','sales_manager'].includes(member.role_code)).map(member=><label key={member.user_id}><input type="checkbox" checked={teamForm.memberIds.includes(member.user_id)} onChange={e=>setTeamForm({...teamForm,memberIds:e.target.checked?[...teamForm.memberIds,member.user_id]:teamForm.memberIds.filter(id=>id!==member.user_id)})}/><span><b>{member.display_name||member.email}</b><small className={member.is_online?'online':''}>{member.is_online?'متصل الآن':'غير متصل'}</small></span></label>)}</fieldset><button className="primary" disabled={busy}>حفظ الفريق</button></form></section><section className="operations-card"><h3>توزيع دفعة العملاء</h3><form className="operations-form" onSubmit={distribute}><label>دفعة العملاء<select required value={distribution.batchId} onChange={e=>setDistribution({...distribution,batchId:e.target.value})}><option value="">اختر الدفعة</option>{batches.filter(batch=>['ready','partially_distributed'].includes(batch.status)).map(batch=><option key={batch.id} value={batch.id}>{batch.file_name} — {batch.valid_rows-batch.assigned_rows} غير موزع</option>)}</select></label><label>الفريق<select required value={distribution.teamId} onChange={e=>setDistribution({...distribution,teamId:e.target.value})}><option value="">اختر الفريق</option>{teams.map(team=><option key={team.id} value={team.id}>{team.name}</option>)}</select></label><label>طريقة التوزيع<select value={distribution.method} onChange={e=>setDistribution({...distribution,method:e.target.value})}><option value="fair">توزيع عادل بالتساوي</option><option value="online_only">المتصلون على النظام فقط</option></select></label><label>آخر موعد للمهام<input required type="datetime-local" value={distribution.dueAt} onChange={e=>setDistribution({...distribution,dueAt:e.target.value})}/></label><div className="distribution-note wide"><b>{distribution.method==='fair'?'التوزيع العادل':'التوزيع على المتصلين'}</b><p>{distribution.method==='fair'?'يبدأ النظام بالموظف الأقل حصولًا على عملاء، ثم يوزع بالتتابع على الفريق.':'لا يتم الإسناد إلا لمن ظهر نشاطه داخل النظام خلال آخر 5 دقائق.'}</p></div><button className="primary wide" disabled={busy}>توزيع العملاء وإنشاء المهام</button></form></section></div>}
        </div>
      </section>
    </div>,document.body)}
  </>;
}
