'use client';

import {useRef,useState} from 'react';
import type {FormEvent,ReactNode} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {
  LEARNING_MODE_LABELS,TRAINING_ROLE_LABELS,TRAINING_UNIT_LABELS,safeTrainingExternalUrl,
} from '../lib/training-journey-contract';
import type {
  LearningMode,TrainingCourse,TrainingEnrollment,TrainingFinance,TrainingHandoff,
  TrainingJourneySnapshot,TrainingMutation,TrainingMutationResult,TrainingOperationsSnapshot,
  TrainingPayload,TrainingPolicy,TrainingQuestion,TrainingSubmission,TrainingUnit,TrainingUnitKind,
} from '../lib/training-journey-contract';
import styles from './training-journey.module.css';

const cx=(...values:Array<string|false|undefined>)=>values.filter(Boolean).join(' ');
const REQUEST_LABELS={transfer:'نقل إلى دفعة',defer:'تأجيل التدريب',withdraw:'انسحاب',access_exception:'استثناء مؤقت للدخول',resume:'استئناف التدريب'};
const STATE_LABELS:Record<string,string>={approved_credit:'ائتمان معتمد',settled:'مسدد',awaiting_payment:'بانتظار السداد',in_grace:'داخل مهلة السداد',pending:'بانتظار المراجعة',pending_verification:'بانتظار تأكيد الدفع',verified:'دفع مؤكد',accepted:'مقبول',completed:'مكتمل',active:'نشط',confirmed:'تسجيل مؤكد',cancelled:'ملغي',withdrawn:'منسحب',in_review:'قيد المراجعة',rejected:'مرفوض',approved:'معتمد',requested:'طلب جديد',open:'مفتوح',planning:'قيد التجهيز',in_progress:'جارٍ التنفيذ',todo:'مطلوب',done:'منجز',draft:'مسودة',published:'منشور',full:'سداد كامل',installments:'أقساط',company_credit:'ائتمان شركة',allowed:'متاح',blocked:'معلق',grace:'داخل المهلة',suspended:'دخول معلق',paid:'مسدد',unpaid:'غير مسدد'};
const REASON_LABELS:Record<string,string>={complete_installment_plan_required:'يجب جدولة كامل قيمة الفاتورة',first_installment_required:'بانتظار تأكيد القسط الأول كاملًا',installment_grace_expired:'انتهت مهلة سداد القسط',company_credit_limit_exceeded:'قيمة التسجيل تتجاوز الائتمان المعتمد',credit_approval_required:'بانتظار اعتماد ائتمان الشركة',full_payment_required:'يلزم استكمال قيمة الفاتورة',invoice_link_required:'بانتظار ربط الفاتورة',admission_confirmation_required:'بانتظار اعتماد القبول',enrollment_deferred:'التسجيل مؤجل',payment_unconfirmed:'بانتظار تأكيد الدفع',payment_not_verified:'بانتظار تأكيد الدفع',finance_not_configured:'لم يكتمل ربط الفاتورة وسياسة السداد',invoice_not_linked:'بانتظار ربط الفاتورة',payment_required:'بانتظار استيفاء السداد',overdue:'انتهت مهلة السداد',installment_overdue:'يوجد قسط تجاوز مهلة السداد',credit_not_approved:'بانتظار اعتماد ائتمان الشركة',credit_expired:'انتهت صلاحية الائتمان',enrollment_inactive:'التسجيل غير نشط',content_incomplete:'لم يكتمل المحتوى المطلوب',required_units_incomplete:'لم يكتمل المحتوى المطلوب',assignment_pending:'واجب ينتظر التصحيح',attendance_below_threshold:'الحضور أقل من النسبة المطلوبة',assessment_below_threshold:'التقييم أقل من درجة الاجتياز',run_not_completed:'الدفعة لم تُغلق بعد',certificate_disabled:'إصدار الشهادة متوقف',version_not_assigned:'بانتظار إسناد المحتوى',learning_version_missing:'بانتظار إسناد المحتوى',sessions_pending:'توجد جلسات لم تكتمل',attendance_incomplete:'تسجيل الحضور غير مكتمل',assessment_missing:'النتيجة النهائية غير مسجلة',no_sessions:'جدول اللقاءات غير مكتمل'};
const label=(value:unknown)=>typeof value==='string'?(STATE_LABELS[value]||REASON_LABELS[value]||value):'—';
const errorText=(error:unknown)=>error instanceof Error?error.message:'تعذر إتمام الإجراء. حاول مرة أخرى.';
const number=(value:unknown)=>new Intl.NumberFormat('ar-SA').format(typeof value==='number'?value:0);
const money=(value:unknown,currency='SAR')=>new Intl.NumberFormat('ar-SA',{style:'currency',currency,maximumFractionDigits:2}).format((typeof value==='number'?value:0)/100);
function date(value?:string|null,timezone='Asia/Riyadh'){if(!value)return 'غير محدد';try{return new Intl.DateTimeFormat('ar-SA',{dateStyle:'medium',timeStyle:'short',timeZone:timezone}).format(new Date(value));}catch{return 'غير محدد';}}
function reasonList(value:{reasonCodes?:string[]}|undefined){return value?.reasonCodes?.map(label).join(' · ')||'';}
function Button({children,primary=false,disabled=false,reason,onClick,type='button'}:{children:ReactNode;primary?:boolean;disabled?:boolean;reason?:string;onClick?:()=>void;type?:'button'|'submit'}){return <button type={type} className={cx(styles.button,primary&&styles.primary)} disabled={disabled} data-block-reason={disabled?reason||'انتظر اكتمال العملية الحالية.':undefined} title={disabled?reason:undefined} onClick={onClick}>{children}</button>;}
function Field({label:fieldLabel,children,hint}:{label:string;children:ReactNode;hint?:string}){return <label className={styles.field}><span>{fieldLabel}</span>{children}{hint&&<small>{hint}</small>}</label>;}
function Empty({title,children}:{title:string;children:ReactNode}){return <div className={styles.empty}><strong>{title}</strong><p>{children}</p></div>;}
function Panel({title,description,actions,children}:{title:string;description?:string;actions?:ReactNode;children:ReactNode}){return <section className={styles.panel}><header className={styles.panelHead}><div><h2>{title}</h2>{description&&<p>{description}</p>}</div>{actions}</header>{children}</section>;}
function Badge({value,good=false,bad=false}:{value:string;good?:boolean;bad?:boolean}){return <span className={cx(styles.badge,good&&styles.good,bad&&styles.bad)}>{label(value)}</span>;}
function Progress({percent}:{percent:number}){const normalized=Math.max(0,Math.min(100,Number.isFinite(percent)?percent:0));return <div className={styles.progress} role="progressbar" aria-label="إتمام المحتوى" aria-valuenow={normalized} aria-valuemin={0} aria-valuemax={100}><span style={{width:`${normalized}%`}}/></div>;}

export default function TrainingJourneyWorkspace({slug,initialData,initialView='overview'}:{slug:string;initialData:TrainingJourneySnapshot;initialView?:string}){
  const router=useRouter();
  const aliases:Record<string,string>={dashboard:'overview',operations:'overview',courses:'content',learners:'enrollments',calendar:'attendance',assessments:'grading',compliance:'readiness',settings:'content'};
  const requestedView=aliases[initialView]||initialView;
  const [view,setView]=useState(['overview','admissions','content','enrollments','requests','tasks','grading','attendance','learning','readiness'].includes(requestedView)?requestedView:'overview');
  const [busy,setBusy]=useState(false);
  const [notice,setNotice]=useState('');
  const [error,setError]=useState('');
  const commands=useRef(new Map<string,{id:string;invitationToken?:string}>());
  const inFlight=useRef(false);
  const [loaded,setLoaded]=useState<{base:TrainingJourneySnapshot;snapshot:TrainingJourneySnapshot;offset:number}|null>(null);
  const [focusedCourseId,setFocusedCourseId]=useState('');
  const data=loaded?.base===initialData?loaded.snapshot:initialData;
  const activeFocusedCourseId=loaded?.base===initialData?focusedCourseId:'';
  const role=data.role;
  const learning=data.learning||{role,courses:[],enrollments:[]};
  const operations=data.operations;
  const pageOffset=loaded?.base===initialData?loaded.offset:(operations?.offset??learning.pagination?.offset??0);
  const pageSize=role==='manager'?(operations?.pageSize||learning.pagination?.limit||50):(learning.pagination?.limit||50);
  const visibleOperationLists=role!=='manager'||!operations?.enabled?[]
    :view==='admissions'?[operations.handoffs]
      :view==='tasks'?[operations.tasks]
        :view==='requests'?[operations.requests]
          :view==='overview'?[operations.handoffs,operations.enrollments,operations.tasks]:[];
  const operationsHasMore=visibleOperationLists.length>0&&(operations?.hasMore??visibleOperationLists.some(items=>items.length>=pageSize));
  const pageHasMore=Boolean(learning.pagination?.hasMore||operationsHasMore);
  const showPagination=Boolean(learning.pagination||visibleOperationLists.length>0);
  async function loadSnapshot(payload:TrainingPayload):Promise<boolean>{
    if(inFlight.current)return false;inFlight.current=true;setBusy(true);setError('');
    try{const response=await fetch('/api/training/snapshot',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tenantSlug:slug,payload:{role,...payload}})});const result=await response.json().catch(()=>null);if(!response.ok)throw Error(result?.error||'تعذر تحميل البيانات. حاول مرة أخرى.');const next=result?.data??result;if(!next||next.tenant?.id!==initialData.tenant.id||next.role!==role)throw Error('تعذر التحقق من بيانات التدريب. حدّث الصفحة.');setLoaded({base:initialData,snapshot:next as TrainingJourneySnapshot,offset:typeof payload.offset==='number'?payload.offset:0});setFocusedCourseId(typeof payload.courseId==='string'?payload.courseId:'');return true;}catch(err){setError(errorText(err));return false;}finally{inFlight.current=false;setBusy(false);}
  }
  const mutate:TrainingMutation=async(action,payload,success)=>{
    if(inFlight.current)return null;
    inFlight.current=true;setBusy(true);setError('');setNotice('');
    const signature=JSON.stringify([action,payload]);
    let command=commands.current.get(signature);
    if(!command){command={id:crypto.randomUUID()};if(action==='issue_invitation'){const bytes=crypto.getRandomValues(new Uint8Array(32));command.invitationToken=Array.from(bytes,n=>n.toString(16).padStart(2,'0')).join('');}commands.current.set(signature,command);}
    try{
      const response=await fetch(`/api/training/${encodeURIComponent(action)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tenantSlug:slug,commandId:command.id,payload:{...payload,...(command.invitationToken?{invitationToken:command.invitationToken}:{})}})});
      const result=await response.json().catch(()=>null);
      if(!response.ok)throw new Error(result?.error||'تعذر تأكيد نتيجة الإجراء. أعد المحاولة بنفس البيانات.');
      if(!result||typeof result!=='object')throw new Error('تعذر تأكيد نتيجة الإجراء. أعد المحاولة بنفس البيانات.');
      const outcome=(result.data??result) as TrainingMutationResult;
      const message=action==='verify_payment'&&outcome.autoAssigned===true
        ?'تم تأكيد الدفعة وإلحاق المتدرب بالدفعة المحددة تلقائيًا.'
        :action==='verify_payment'&&outcome.assignmentIssue
          ?'تم تأكيد الدفعة وحفظها. يحتاج إلحاق المتدرب إلى مراجعة القبول؛ لم تُكرر الدفعة المالية.'
          :success;
      commands.current.delete(signature);setNotice(message);router.refresh();
      return outcome;
    }catch(err){setError(errorText(err));return null;}
    finally{inFlight.current=false;setBusy(false);}
  };
  const tabs=role==='manager'?[['overview','نظرة عامة'],['admissions','القبول والسداد'],['content','الدورات والمحتوى'],['enrollments','التسجيلات والدعوات'],['requests','طلبات المتدربين'],['tasks','مهام التشغيل'],['grading','تصحيح الواجبات'],['attendance','الحضور'],['readiness','جاهزية البرنامج']]:role==='instructor'?[['overview','دفعاتي'],['grading','تصحيح الواجبات'],['attendance','الحضور']]:[['overview','دوراتي'],['learning','مساحة التعلم'],['requests','طلباتي وشهاداتي']];
  const count=learning.enrollments.length;
  const isManager=role==='manager';
  return <main className={styles.workspace} dir="rtl" aria-busy={busy}>
    <header className={styles.header}><div><span className={styles.eyebrow}>منصة التدريب التفاعلي · {data.tenant.name}</span><h1>{isManager?'رحلة التدريب المتكاملة':role==='instructor'?'مساحة المحاضر':'مساحتي التدريبية'}</h1><p>{isManager?'التسجيل والسداد والتعلم والشهادة، في رحلة واحدة مرتبطة بأودير.':role==='instructor'?'تابع دفعاتك، سجل الحضور، وقدم ملاحظات واضحة على أعمال المتدربين.':'تعرف على خطوتك التالية وتابع تعلمك ومواعيدك ونتائجك.'}</p></div><div className={styles.actions}><span className={styles.role}>{TRAINING_ROLE_LABELS[role]}</span>{isManager&&<Link className={styles.button} href={`/tenant/${encodeURIComponent(slug)}/lms/paths`}>استعراض شاشات التطوير</Link>}<Button disabled={busy} onClick={()=>router.refresh()}>تحديث البيانات</Button></div></header>
    {notice&&<div className={styles.notice} role="status">{notice}</div>}{error&&<div className={cx(styles.notice,styles.error)} role="alert">{error}</div>}
    <nav className={styles.tabs} aria-label="أقسام التدريب">{tabs.filter(([key])=>role!=='manager'||data.viewer.canManageLearning!==false||!['content','enrollments','grading','attendance','readiness'].includes(key)).map(([key,title])=><button key={key} type="button" className={styles.tab} aria-current={view===key} onClick={()=>{setView(key);if(activeFocusedCourseId&&key!=='content')void loadSnapshot({offset:0});}}>{title}</button>)}</nav>
    {view==='overview'&&<>
      <section className={styles.stats} aria-label="مؤشرات التدريب"><Stat title={isManager?'التسجيلات في الصفحة':'تسجيلاتي التدريبية'} value={count} detail="حسب صلاحية حسابك"/><Stat title="اكتمل المحتوى" value={learning.enrollments.filter(item=>item.progress?.totalUnits>0&&item.progress.percent>=100).length} detail="حالة التعلم مستقلة عن السداد"/><Stat title="الواجبات بانتظار التصحيح" value={(learning.submissions||[]).filter(item=>item.grade==null).length} detail={role==='learner'?'نتائج أعمالك':'ضمن الدفعات المتاحة لك'}/><Stat title={isManager?'مهام تحتاج متابعة':'الشهادات الصادرة'} value={isManager?(operations?.tasks||[]).filter(item=>!['done','completed','cancelled'].includes(item.status)).length:learning.enrollments.filter(item=>item.certificate?.status==='issued').length} detail={isManager?'مسؤول واضح لكل إجراء':'بعد استيفاء شروط الإكمال'}/></section>
      {isManager&&<Panel title="حلقة التشغيل" description="كل مرحلة تحتفظ بحالتها، وتنتقل المسؤولية للموظف المناسب."><ol className={styles.steps}><li><strong>١. تسجيل وقبول</strong><span>ملف متدرب واحد ومقعد مناسب</span></li><li><strong>٢. سداد مؤكد</strong><span>فاتورة مرتبطة وخطة سداد واضحة</span></li><li><strong>٣. تعلم ومتابعة</strong><span>محتوى وحضور وواجبات وتقييم</span></li><li><strong>٤. إكمال وشهادة</strong><span>تحقق من الشروط واعتماد الإصدار</span></li></ol><div className={styles.actions}>{data.viewer.canReadAdmissions&&<Link className={styles.button} href={`/tenant/${encodeURIComponent(slug)}/admissions`}>التسجيل والقبول</Link>}{data.viewer.canReadAccounting&&<Link className={styles.button} href={`/tenant/${encodeURIComponent(slug)}/accounting`}>الحسابات والفوترة</Link>}{data.viewer.canManageCourses&&<Link className={styles.button} href={`/tenant/${encodeURIComponent(slug)}/courses`}>الدورات والدفعات</Link>}</div></Panel>}
      <EnrollmentCards enrollments={learning.enrollments} onLearn={()=>setView('learning')} role={role}/>
    </>}
    {view==='admissions'&&isManager&&<AdmissionOperations operations={operations} slug={slug} tenantId={data.tenant.id} busy={busy} mutate={mutate}/>}
    {view==='content'&&isManager&&<CourseContent courses={learning.courses} focusedCourseId={activeFocusedCourseId} onFocusCourse={courseId=>loadSnapshot({courseId,offset:0})} onClearFocus={()=>loadSnapshot({offset:0})} busy={busy} mutate={mutate}/>}
    {view==='enrollments'&&isManager&&<EnrollmentManagement data={data} busy={busy} mutate={mutate}/>}
    {view==='requests'&&<><RequestWorkspace data={data} busy={busy} mutate={mutate}/>{role==='learner'&&<LearnerResults submissions={learning.submissions||[]}/>}</>}
    {view==='tasks'&&isManager&&<TaskWorkspace operations={operations} slug={slug} timezone={data.tenant.timezone} busy={busy} mutate={mutate}/>}
    {view==='grading'&&role!=='learner'&&<Grading submissions={learning.submissions||[]} busy={busy} mutate={mutate}/>}
    {view==='attendance'&&role!=='learner'&&<Attendance enrollments={learning.enrollments} busy={busy} mutate={mutate}/>}
    {view==='readiness'&&isManager&&<Readiness courses={learning.courses}/>}
    {view==='learning'&&role==='learner'&&<LearningSpace enrollments={learning.enrollments} courses={learning.courses} busy={busy} mutate={mutate}/>}
    {showPagination&&<nav className={styles.pagination} aria-label="صفحات البيانات"><Button disabled={busy||pageOffset===0} reason="هذه أول صفحة." onClick={()=>void loadSnapshot({offset:Math.max(0,pageOffset-pageSize),...(activeFocusedCourseId?{courseId:activeFocusedCourseId}:{})})}>الصفحة السابقة</Button><span>صفحة {number(Math.floor(pageOffset/pageSize)+1)}</span><Button disabled={busy||!pageHasMore||pageOffset+pageSize>100000} reason="لا توجد نتائج إضافية في هذا العرض." onClick={()=>void loadSnapshot({offset:pageOffset+pageSize,...(activeFocusedCourseId?{courseId:activeFocusedCourseId}:{})})}>الصفحة التالية</Button></nav>}
  </main>;
}
function Stat({title,value,detail}:{title:string;value:number;detail:string}){return <article className={styles.stat}><span>{title}</span><strong>{number(value)}</strong><small>{detail}</small></article>;}
function EnrollmentCards({enrollments,onLearn,role}:{enrollments:TrainingEnrollment[];onLearn:()=>void;role:string}){return <Panel title={role==='learner'?'دوراتي وخطوتي التالية':'التسجيلات التدريبية'} description={role==='instructor'?'تظهر هنا التسجيلات التابعة للدفعات المسندة لحسابك.':undefined}>{!enrollments.length?<Empty title="لا توجد تسجيلات متاحة بعد">{role==='learner'?'بعد اعتماد قبولك وإسناد الدورة، ستظهر رحلتك التدريبية هنا.':'تظهر هنا التسجيلات الحقيقية بعد اكتمال القبول وإسناد محتوى التدريب.'}</Empty>:<div className={styles.gridThree}>{enrollments.map(item=><article className={styles.card} key={item.id}><div className={styles.row}><Badge value={item.status}/>{item.certificate?.status==='issued'&&<Badge value="صدرت الشهادة" good/>}</div><h3>{item.courseTitle}</h3><p>{item.runTitle||'تعلم ذاتي دون دفعة'}</p>{role!=='learner'&&<p>{item.studentName}</p>}<Progress percent={item.progress?.percent||0}/><div className={styles.row}><span className={styles.secondaryText}>أكملت {number(item.progress?.completedUnits)} من {number(item.progress?.totalUnits)} نشاطًا</span><strong>{number(item.progress?.percent)}٪</strong></div><p>{reasonList(item.financialAccess)}</p>{role==='learner'&&<div className={styles.actions}><Button primary onClick={onLearn}>فتح مساحة التعلم</Button></div>}</article>)}</div>}</Panel>;}

function CourseContent({courses,focusedCourseId,onFocusCourse,onClearFocus,busy,mutate}:{courses:TrainingCourse[];focusedCourseId:string;onFocusCourse:(courseId:string)=>Promise<boolean>;onClearFocus:()=>Promise<boolean>;busy:boolean;mutate:TrainingMutation}){
  const [courseId,setCourseId]=useState(courses[0]?.id||'');
  const course=courses.find(item=>item.id===courseId)||courses[0];
  const [versionId,setVersionId]=useState('latest');
  const version=versionId==='latest'?course?.versions[0]:course?.versions.find(item=>item.id===versionId);
  return <Panel title="المحتوى وشروط الإكمال" description="الدورة أصل واحد، والمحتوى يُنشر في إصدارات ثابتة للحفاظ على رحلة كل دفعة.">
    {!course?<Empty title="أضف أول دورة من أودير">ابدأ بملف الدورة في قسم الدورات، ثم جهز محتواها وشروط إكمالها هنا.</Empty>:<>
      <div className={styles.formGrid}><Field label="الدورة"><select value={course.id} onChange={event=>{setCourseId(event.target.value);setVersionId('latest');void onFocusCourse(event.target.value);}}>{courses.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></Field><Field label="إصدار المحتوى"><select value={versionId} onChange={event=>setVersionId(event.target.value)}><option value="latest">آخر إصدار متاح</option><option value="">إعداد إصدار جديد</option>{course.versions.map(item=><option key={item.id} value={item.id}>الإصدار {item.version} · {label(item.status)}</option>)}</select></Field></div>
      {focusedCourseId&&<div className={styles.actions}><Button disabled={busy} onClick={()=>void onClearFocus()}>عرض جميع الدورات</Button></div>}
      {focusedCourseId!==course.id?<div className={styles.info}><p>افتح محتوى الدورة لتحميل آخر إصدار وتعديل المسودة.</p><Button disabled={busy} onClick={()=>void onFocusCourse(course.id)}>فتح محرر المحتوى</Button></div>:(version?.status==='published'||(version&&version.id!==course.versions[0]?.id))?<><div className={styles.info}>هذا إصدار محفوظ. يحتفظ المتدربون بنسختهم وشروط إكمالها؛ يمكن تعديل أحدث مسودة أو إعداد إصدار جديد.</div><div className={styles.stack}>{version.units.map(unit=><div key={unit.id} className={styles.card}><strong>{unit.title}</strong><p>{TRAINING_UNIT_LABELS[unit.kind]} · {unit.required?'مطلوب للإكمال':'إثرائي'}</p></div>)}</div></>:<CourseEditor key={`${course.id}:${version?.id||'new'}`} course={course} initialVersion={version} busy={busy} mutate={mutate}/>}
    </>}
  </Panel>;
}
type DraftUnit=Omit<TrainingUnit,'id'>&{id?:string};
const newUnit=():DraftUnit=>({title:'',kind:'text',required:true,minimumSeconds:0,body:'',url:'',maxAttempts:3,passPercent:70,questions:[]});
function CourseEditor({course,initialVersion,busy,mutate}:{course:TrainingCourse;initialVersion?:TrainingCourse['versions'][number];busy:boolean;mutate:TrainingMutation}){
  const [title,setTitle]=useState(initialVersion?.title||course.title);
  const [mode,setMode]=useState<LearningMode>(initialVersion?.learningMode||'blended');
  const [policy,setPolicy]=useState<TrainingPolicy>(initialVersion?.policy||{minAttendancePercent:75,minAssessmentPercent:70,requireCompletedRun:true,certificateEnabled:true,termsVersion:'',supportEmail:''});
  const [units,setUnits]=useState<DraftUnit[]>(initialVersion?.units?.length?initialVersion.units.map(unit=>({...unit})):[]);
  const [savedVersion,setSavedVersion]=useState(initialVersion?.id||'');
  const [dirty,setDirty]=useState(!initialVersion);
  const [reviewed,setReviewed]=useState(false);
  const change=()=>{setDirty(true);setReviewed(false);};
  function updateUnit(index:number,patch:Partial<DraftUnit>){change();setUnits(current=>current.map((unit,i)=>i===index?{...unit,...patch}:unit));}
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const result=await mutate('save_draft',{courseId:course.id,...(savedVersion?{versionId:savedVersion}:{}),title:title.trim(),learningMode:mode,policy,units:units.map((unit,index)=>({...unit,position:index+1}))},'تم حفظ مسودة المحتوى. راجعها قبل النشر.');if(typeof result?.versionId==='string'){setSavedVersion(result.versionId);setDirty(false);}}
  return <form className={styles.form} onSubmit={save}>
    <div className={styles.divider}/><div className={styles.formGrid}><Field label="عنوان الإصدار"><input value={title} onChange={event=>{setTitle(event.target.value);change();}} required maxLength={180}/></Field><Field label="طريقة التعلم"><select value={mode} onChange={event=>{setMode(event.target.value as LearningMode);change();}}>{Object.entries(LEARNING_MODE_LABELS).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></Field><Field label="نسبة الحضور المطلوبة" hint="تحددها سياسة البرنامج؛ التعلم الذاتي يعتمد على إكمال المحتوى."><input type="number" min={0} max={100} value={policy.minAttendancePercent} onChange={event=>{setPolicy({...policy,minAttendancePercent:Number(event.target.value)});change();}} required/></Field><Field label="درجة الاجتياز المطلوبة"><input type="number" min={0} max={100} value={policy.minAssessmentPercent} onChange={event=>{setPolicy({...policy,minAssessmentPercent:Number(event.target.value)});change();}} required/></Field><Field label="مرجع شروط البرنامج"><input value={policy.termsVersion} onChange={event=>{setPolicy({...policy,termsVersion:event.target.value});change();}} maxLength={100} required placeholder="مثل رقم نسخة السياسة المعتمدة"/></Field><Field label="بريد دعم المتدربين"><input type="email" dir="ltr" value={policy.supportEmail} onChange={event=>{setPolicy({...policy,supportEmail:event.target.value});change();}} maxLength={254} required/></Field></div>
    <div className={styles.actions}><label className={styles.check}><input type="checkbox" checked={policy.requireCompletedRun} onChange={event=>{setPolicy({...policy,requireCompletedRun:event.target.checked});change();}}/>يشترط إغلاق الدفعة عند وجود لقاءات مباشرة</label><label className={styles.check}><input type="checkbox" checked={policy.certificateEnabled} onChange={event=>{setPolicy({...policy,certificateEnabled:event.target.checked});change();}}/>إتاحة الشهادة عند استيفاء الشروط</label></div>
    <div className={styles.panelHead}><div><h3>تسلسل المحتوى</h3><p>رتب الدروس والاختبارات والواجبات بالترتيب الذي يتبعه المتدرب.</p></div><Button onClick={()=>{setUnits([...units,newUnit()]);change();}}>إضافة نشاط</Button></div>
    {!units.length&&<Empty title="ابدأ بأول نشاط">أضف درسًا أو فيديو أو اختبارًا أو واجبًا، وحدد هل يلزم إكماله.</Empty>}
    {units.map((unit,index)=><fieldset className={styles.question} key={unit.id||index}><legend>النشاط {number(index+1)}</legend><div className={styles.formGrid}><Field label="عنوان النشاط"><input value={unit.title} onChange={event=>updateUnit(index,{title:event.target.value})} maxLength={200} required/></Field><Field label="نوع النشاط"><select value={unit.kind} onChange={event=>updateUnit(index,{kind:event.target.value as TrainingUnitKind})}>{Object.entries(TRAINING_UNIT_LABELS).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></Field><div className={styles.full}><Field label={unit.kind==='assignment'?'تعليمات الواجب':'محتوى النشاط وتعليماته'}><textarea value={unit.body||''} onChange={event=>updateUnit(index,{body:event.target.value})} maxLength={12000} required/></Field></div>{['video','link'].includes(unit.kind)&&<div className={styles.full}><Field label="رابط المحتوى الآمن"><input type="url" dir="ltr" pattern="https://.*" value={unit.url||''} onChange={event=>updateUnit(index,{url:event.target.value})} maxLength={2000} required placeholder="https://"/></Field></div>}<Field label="الحد الأدنى للوقت بالثواني" hint="يُتحقق منه عند إكمال النشاط."><input type="number" min={0} max={86400} value={unit.minimumSeconds} onChange={event=>updateUnit(index,{minimumSeconds:Number(event.target.value)})}/></Field><label className={styles.check}><input type="checkbox" checked={unit.required} onChange={event=>updateUnit(index,{required:event.target.checked})}/>نشاط مطلوب للإكمال</label></div>
      {unit.kind==='quiz'&&<QuizEditor unit={unit} onChange={patch=>updateUnit(index,patch)}/>}
      <div className={styles.actions}><Button disabled={index===0} reason="هذا أول نشاط في التسلسل." onClick={()=>{const next=[...units];[next[index-1],next[index]]=[next[index],next[index-1]];setUnits(next);change();}}>تقديم النشاط</Button><Button onClick={()=>{setUnits(units.filter((_,i)=>i!==index));change();}}>إزالة من المسودة</Button></div>
    </fieldset>)}
    <div className={styles.actions}><Button primary type="submit" disabled={busy||!units.length} reason={!units.length?'أضف نشاطًا واحدًا على الأقل.':undefined}>حفظ المسودة</Button><span className={styles.secondaryText}>{dirty?'توجد تغييرات تحتاج الحفظ.':'المسودة محفوظة.'}</span></div>
    {savedVersion&&<div className={styles.info}><label className={styles.check}><input type="checkbox" checked={reviewed} disabled={dirty} onChange={event=>setReviewed(event.target.checked)}/>راجعت المحتوى والأسئلة وصحة الإجابات وشروط الإكمال وبيانات الدعم.</label><div className={styles.actions}><Button disabled={busy||dirty||!reviewed} reason={dirty?'احفظ التغييرات قبل نشر الإصدار.':'أكد المراجعة البشرية قبل النشر.'} onClick={async()=>{const result=await mutate('publish_version',{versionId:savedVersion,humanReviewed:true},'تم نشر إصدار المحتوى وأصبح متاحًا للإسناد.');if(result)setReviewed(false);}}>نشر الإصدار</Button></div></div>}
  </form>;
}
function QuizEditor({unit,onChange}:{unit:DraftUnit;onChange:(patch:Partial<DraftUnit>)=>void}){
  const questions=unit.questions||[];
  function updateQuestion(index:number,patch:Partial<TrainingQuestion>){onChange({questions:questions.map((question,i)=>i===index?{...question,...patch}:question)});}
  return <div className={styles.stack}><div className={styles.formGrid}><Field label="عدد المحاولات"><input type="number" min={1} max={20} value={unit.maxAttempts||3} onChange={event=>onChange({maxAttempts:Number(event.target.value)})}/></Field><Field label="درجة اجتياز الاختبار"><input type="number" min={0} max={100} value={unit.passPercent??70} onChange={event=>onChange({passPercent:Number(event.target.value)})}/></Field></div>{questions.map((question,index)=><fieldset className={styles.question} key={question.id}><legend>السؤال {number(index+1)}</legend><div className={styles.form}><Field label="نص السؤال"><input value={question.prompt} maxLength={1000} required onChange={event=>updateQuestion(index,{prompt:event.target.value})}/></Field><div className={styles.formGrid}>{question.options.map((option,optionIndex)=><Field key={optionIndex} label={`الاختيار ${number(optionIndex+1)}`}><input value={option} maxLength={500} required onChange={event=>updateQuestion(index,{options:question.options.map((value,i)=>i===optionIndex?event.target.value:value)})}/></Field>)}</div><Field label="الإجابة الصحيحة"><select value={question.correctOptionIndex??0} onChange={event=>updateQuestion(index,{correctOptionIndex:Number(event.target.value)})}>{question.options.map((_,i)=><option key={i} value={i}>الاختيار {number(i+1)}</option>)}</select></Field><Button onClick={()=>onChange({questions:questions.filter((_,i)=>i!==index)})}>إزالة السؤال</Button></div></fieldset>)}<div><Button onClick={()=>onChange({questions:[...questions,{id:crypto.randomUUID(),prompt:'',options:['','','',''],correctOptionIndex:0}]})}>إضافة سؤال</Button></div></div>;
}

function AdmissionOperations({operations,slug,tenantId,busy,mutate}:{operations?:TrainingOperationsSnapshot|null;slug:string;tenantId:string;busy:boolean;mutate:TrainingMutation}){
  type OptionPage={base:TrainingOperationsSnapshot;invoices:TrainingOperationsSnapshot['invoices'];payments:NonNullable<TrainingOperationsSnapshot['payments']>;runs:TrainingOperationsSnapshot['runs'];offset:number;hasMore:boolean};
  const [optionPage,setOptionPage]=useState<OptionPage|null>(null);
  const [optionsBusy,setOptionsBusy]=useState(false);
  const [optionsError,setOptionsError]=useState('');
  const optionsRequest=useRef(false);
  const currentOptions=optionPage?.base===operations?optionPage:null;
  const expanded=operations&&currentOptions?{...operations,invoices:currentOptions.invoices,payments:currentOptions.payments,runs:currentOptions.runs}:operations;
  const optionOffset=currentOptions?.offset??operations?.offset??0;
  const optionSize=operations?.pageSize||50;
  const hasMoreOptions=currentOptions?.hasMore??Boolean(operations&&[operations.invoices,operations.payments||[],operations.runs].some(items=>items.length>=optionSize));
  async function loadOptions(){
    if(!operations||busy||optionsRequest.current||optionOffset+optionSize>100000)return;
    optionsRequest.current=true;setOptionsBusy(true);setOptionsError('');
    try{
      const offset=optionOffset+optionSize;
      const result=await fetch('/api/training/snapshot',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tenantSlug:slug,payload:{role:'manager',offset}})});
      const payload=await result.json().catch(()=>null);
      if(!result.ok)throw Error(payload?.error||'تعذر تحميل خيارات إضافية. حاول مرة أخرى.');
      const next=payload?.data??payload;
      if(next?.role!=='manager'||next.tenant?.id!==tenantId||next.tenant?.slug!==slug||!next.operations?.enabled)throw Error('تعذر التحقق من خيارات التسجيل. حدّث الصفحة.');
      const extra=next.operations as TrainingOperationsSnapshot;
      const merge=<T extends {id:string}>(existing:T[],incoming:T[])=>Array.from(new Map([...existing,...incoming].map(item=>[item.id,item])).values());
      setOptionPage({base:operations,offset,invoices:merge(expanded?.invoices||[],extra.invoices),payments:merge(expanded?.payments||[],extra.payments||[]),runs:merge(expanded?.runs||[],extra.runs),hasMore:[extra.invoices,extra.payments||[],extra.runs].some(items=>items.length>=optionSize)});
    }catch(err){setOptionsError(errorText(err));}
    finally{optionsRequest.current=false;setOptionsBusy(false);}
  }
  return <Panel title="القبول والسداد وفتح التدريب" description="تأكيد التحصيل لا يكرر الدفعة المالية. لكل تسجيل فاتورة وسياسة وصول واضحة." actions={<Link className={styles.button} href={`/tenant/${encodeURIComponent(slug)}/admissions`}>فتح طلبات التسجيل</Link>}>
    {optionsError&&<div className={cx(styles.notice,styles.error)} role="alert">{optionsError}</div>}
    {operations?.enabled&&hasMoreOptions&&<div className={styles.info}><p>هل الفاتورة أو الدفعة المطلوبة غير ظاهرة؟ حمّل خيارات إضافية مع الاحتفاظ بطلبات التسجيل الحالية.</p><Button disabled={busy||optionsBusy||optionOffset+optionSize>100000} onClick={()=>void loadOptions()}>{optionsBusy?'جارٍ تحميل الخيارات…':'تحميل خيارات إضافية'}</Button></div>}
    {!expanded?.enabled?<Empty title="التشغيل المتكامل قيد التجهيز">ستظهر طلبات القبول بعد تفعيل دورة التشغيل لهذه المنشأة.</Empty>:!expanded.handoffs.length?<Empty title="لا توجد طلبات تسجيل في هذه الصفحة">تصل الطلبات من قنوات التسجيل الحالية في أودير، وتُستكمل هنا علاقتها بالسداد والتدريب.</Empty>:<div className={styles.stack}>{expanded.handoffs.map(handoff=><HandoffCard key={handoff.id} handoff={handoff} operations={expanded} busy={busy||optionsBusy} mutate={mutate}/>)}</div>}
  </Panel>;
}
function FinanceSummary({financial}:{financial?:TrainingFinance}){if(!financial)return <p className={styles.secondaryText}>لم يكتمل ربط الوضع المالي بعد.</p>;const reasons=Array.isArray(financial.reasonCodes)?financial.reasonCodes.filter((value):value is string=>typeof value==='string'):[];return <><dl className={styles.policy}><div><dt>حالة السداد</dt><dd>{label(financial.financialStatus)}</dd></div>{typeof financial.paidMinor==='number'&&<div><dt>المبلغ المؤكد</dt><dd>{money(financial.paidMinor,financial.currency||'SAR')}</dd></div>}{typeof financial.outstandingMinor==='number'&&<div><dt>المتبقي</dt><dd>{money(financial.outstandingMinor,financial.currency||'SAR')}</dd></div>}</dl><div className={styles.row}><Badge value={financial.trainingAllowed===true?'الدخول متاح':'الدخول بانتظار الاستيفاء'} good={financial.trainingAllowed===true}/><span className={styles.secondaryText}>{reasons.map(label).join(' · ')||reasonList(financial)}</span></div>{typeof financial.graceEndsOn==='string'&&<p className={styles.secondaryText}>نهاية مهلة السداد: {financial.graceEndsOn}</p>}</>;}
function HandoffCard({handoff,operations,busy,mutate}:{handoff:TrainingHandoff;operations:TrainingOperationsSnapshot;busy:boolean;mutate:TrainingMutation}){
  const [invoiceId,setInvoiceId]=useState(handoff.financial?.invoiceId||'');
  const [policy,setPolicy]=useState(handoff.financial?.policy||'full');
  const [sponsor,setSponsor]=useState(Boolean(handoff.financial?.sponsor));
  const [runId,setRunId]=useState(handoff.courseRunId||'');
  const [selfpaced,setSelfpaced]=useState(false);
  const [paymentId,setPaymentId]=useState('');
  const [creditAmount,setCreditAmount]=useState('');
  const [creditExpiry,setCreditExpiry]=useState('');
  const [creditReason,setCreditReason]=useState('');
  const chosenInvoice=operations.invoices.find(item=>item.id===invoiceId);
  const payments=(operations.payments||[]).filter(item=>item.customerAccountId===chosenInvoice?.customerAccountId);
  const runs=operations.runs.filter(item=>item.courseId===handoff.courseId&&!['cancelled','completed'].includes(item.status));
  return <article className={styles.card}><div className={styles.row}><div><h3>{handoff.contactName}</h3><p>{handoff.courseTitle}</p></div><div className={styles.actions}><Badge value={handoff.status}/><Badge value={handoff.paymentStatus} good={handoff.paymentStatus==='verified'}/></div></div><FinanceSummary financial={handoff.financial}/>
    {operations.capabilities.canVerifyPayments&&<details className={styles.details}><summary>ربط الفاتورة وسياسة السداد</summary><form className={styles.form} onSubmit={event=>{event.preventDefault();void mutate('configure_finance',{handoffId:handoff.id,invoiceId,policy,sponsor},'تم ربط التسجيل بالفاتورة وسياسة السداد.');}}><div className={styles.formGrid}><Field label="الفاتورة" hint="اختر فاتورة المتدرب أو الشركة التي تتحمل الرسوم."><select value={invoiceId} onChange={event=>setInvoiceId(event.target.value)} required><option value="">اختر الفاتورة</option>{operations.invoices.map(item=><option key={item.id} value={item.id}>{item.number} · {item.customerName} · {money(item.totalMinor,item.currency)}</option>)}</select></Field><Field label="سياسة السداد"><select value={policy} onChange={event=>setPolicy(event.target.value as typeof policy)}><option value="full">سداد كامل قبل فتح التدريب</option><option value="installments">أول قسط مؤكد ثم متابعة الخطة</option><option value="company_credit">ائتمان شركة يحتاج اعتمادًا</option></select></Field></div><label className={styles.check}><input type="checkbox" checked={sponsor} onChange={event=>setSponsor(event.target.checked)}/>الفاتورة على جهة راعية أو شركة</label>{policy==='installments'&&<p className={styles.info}>تُستخدم خطة الأقساط المسجلة في الحسابات، بمهلة {number(operations.settings.graceDays)} أيام عند التأخر.</p>}<div><Button primary type="submit" disabled={busy}>حفظ الربط</Button></div></form></details>}
    {operations.capabilities.canVerifyPayments&&<details className={styles.details}><summary>تأكيد دفعة مالية</summary><form className={styles.inlineForm} onSubmit={event=>{event.preventDefault();void mutate('verify_payment',{handoffId:handoff.id,paymentId},'تم تأكيد الدفعة. يُفتح التدريب بعد استكمال المستحق واعتماد القبول.');}}><Field label="الدفعة المسجلة في الحسابات"><select required value={paymentId} onChange={event=>setPaymentId(event.target.value)}><option value="">اختر الدفعة المرتبطة بالدافع</option>{payments.map(item=><option key={item.id} value={item.id}>{item.number} · {money(item.amountMinor)} · {label(item.status)}</option>)}</select></Field><Button type="submit" primary disabled={busy||!payments.length} reason="اربط الفاتورة وسجل الدفعة في الحسابات أولًا.">تأكيد التحصيل</Button></form></details>}
    {operations.capabilities.canApproveCredit&&policy==='company_credit'&&<details className={styles.details}><summary>اعتماد ائتمان الشركة</summary><form className={styles.form} onSubmit={event=>{event.preventDefault();void mutate('approve_credit',{handoffId:handoff.id,limitMinor:Math.round(Number(creditAmount)*100),expiresOn:creditExpiry,reason:creditReason},'تم اعتماد ائتمان الشركة، ويمكن استكمال القبول ضمن الحد والمدة المحددين.');}}><div className={styles.formGrid}><Field label="حد الائتمان بالريال"><input type="number" min="0.01" step="0.01" value={creditAmount} onChange={event=>setCreditAmount(event.target.value)} required/></Field><Field label="تاريخ انتهاء الاعتماد"><input type="date" value={creditExpiry} onChange={event=>setCreditExpiry(event.target.value)} required/></Field></div><Field label="مبرر الاعتماد"><textarea value={creditReason} onChange={event=>setCreditReason(event.target.value)} minLength={5} maxLength={2000} required/></Field><div><Button type="submit" disabled={busy}>اعتماد الائتمان</Button></div></form></details>}
    {operations.capabilities.canManage&&!handoff.enrollmentId&&<details className={styles.details}><summary>إسناد التدريب وإتمام القبول</summary><form className={styles.form} onSubmit={event=>{event.preventDefault();void mutate('confirm_admission',{handoffId:handoff.id,...(selfpaced?{deliveryMode:'selfpaced'}:{courseRunId:runId})},'تم إتمام القبول وإسناد التدريب.');}}><label className={styles.check}><input type="checkbox" checked={selfpaced} onChange={event=>setSelfpaced(event.target.checked)}/>تعلم ذاتي دون دفعة مجدولة</label>{!selfpaced&&<Field label="الدفعة المناسبة"><select value={runId} onChange={event=>setRunId(event.target.value)} required><option value="">اختر الدفعة</option>{runs.map(item=><option key={item.id} value={item.id}>{item.title} · {label(item.status)}{item.capacity?` · ${item.enrolledCount||0} / ${item.capacity}`:''}</option>)}</select></Field>}<p className={styles.secondaryText}>يتحقق النظام من السداد والقبول والسعة قبل إنشاء التسجيل.</p><div><Button type="submit" primary disabled={busy}>إتمام القبول</Button></div></form></details>}
  </article>;
}

function EnrollmentManagement({data,busy,mutate}:{data:TrainingJourneySnapshot;busy:boolean;mutate:TrainingMutation}){
  const enrollments=(data.learning?.enrollments||[]);
  const [selected,setSelected]=useState(enrollments[0]?.id||'');
  const enrollment=enrollments.find(item=>item.id===selected)||enrollments[0];
  return <Panel title="التسجيلات وإتاحة المحتوى" description="أسند الإصدار المناسب، ثم جهز دعوة المتدرب. الدعوة تمنح وصولًا لحسابه الدراسي فقط.">{!enrollment?<Empty title="لا توجد تسجيلات مكتملة بعد">أكمل قبول المتدرب وإسناده للتدريب أولًا.</Empty>:<><Field label="تسجيل المتدرب"><select value={enrollment.id} onChange={event=>setSelected(event.target.value)}>{enrollments.map(item=><option key={item.id} value={item.id}>{item.studentName} · {item.courseTitle} · {item.runTitle||'تعلم ذاتي'}</option>)}</select></Field><EnrollmentEditor key={enrollment.id} enrollment={enrollment} data={data} busy={busy} mutate={mutate}/></>}</Panel>;
}
function EnrollmentEditor({enrollment,data,busy,mutate}:{enrollment:TrainingEnrollment;data:TrainingJourneySnapshot;busy:boolean;mutate:TrainingMutation}){
  const versions=(data.learning?.courses||[]).find(item=>item.id===enrollment.courseId)?.versions.filter(item=>item.status==='published')||[];
  const [versionId,setVersionId]=useState(enrollment.versionId||'');
  const [email,setEmail]=useState(enrollment.studentEmail||'');
  const [invite,setInvite]=useState('');
  const [copied,setCopied]=useState(false);
  const [instructorId,setInstructorId]=useState('');
  return <div className={styles.stack}><FinanceSummary financial={enrollment.financialAccess}/><form className={styles.inlineForm} onSubmit={event=>{event.preventDefault();void mutate('assign_version',{enrollmentId:enrollment.id,versionId},'تم إسناد إصدار المحتوى للتسجيل.');}}><Field label="إصدار المحتوى المنشور"><select required value={versionId} onChange={event=>setVersionId(event.target.value)}><option value="">اختر إصدارًا</option>{versions.map(item=><option key={item.id} value={item.id}>الإصدار {item.version} · {LEARNING_MODE_LABELS[item.learningMode]}</option>)}</select></Field><Button type="submit" disabled={busy||!versions.length} reason="انشر إصدارًا لهذه الدورة أولًا.">إسناد المحتوى</Button></form>
    <form className={styles.form} onSubmit={async event=>{event.preventDefault();setInvite('');setCopied(false);const result=await mutate('issue_invitation',{studentId:enrollment.studentId,email:email.trim().toLowerCase()},'تم إنشاء رابط الدعوة. يمكنك نسخه ومشاركته مع المتدرب.');if(typeof result?.invitationUrl==='string')setInvite(result.invitationUrl);}}><Field label="بريد المتدرب" hint="يجب أن يطابق البريد الذي يستخدمه المتدرب لقبول الدعوة."><input type="email" value={email} onChange={event=>{setEmail(event.target.value);setInvite('');}} maxLength={254} required dir="ltr"/></Field><div><Button type="submit" disabled={busy}>إنشاء دعوة آمنة</Button></div></form>
    {invite&&<div className={styles.info}><Field label="رابط تفعيل حساب المتدرب"><input readOnly value={invite} dir="ltr" onFocus={event=>event.target.select()}/></Field><div className={styles.actions}><Button onClick={async()=>{try{await navigator.clipboard.writeText(invite);setCopied(true);}catch{setCopied(false);}}}>{copied?'تم نسخ الرابط':'نسخ الرابط'}</Button><span className={styles.secondaryText}>لم تُرسل الدعوة تلقائيًا. شاركها مع صاحب البريد فقط.</span></div></div>}
    {enrollment.runId&&<details className={styles.details}><summary>إسناد محاضر للدفعة</summary><form className={styles.inlineForm} onSubmit={event=>{event.preventDefault();void mutate('assign_instructor',{runId:enrollment.runId,subjectId:instructorId,active:true},'تم إسناد المحاضر للدفعة.');}}><Field label="حساب المحاضر"><select required value={instructorId} onChange={event=>setInstructorId(event.target.value)}><option value="">اختر المحاضر</option>{(data.learning?.instructorCandidates||[]).map(item=><option key={item.subjectId} value={item.subjectId}>{item.name}</option>)}</select></Field><Button type="submit" disabled={busy||!data.learning?.instructorCandidates?.length} reason="أضف حساب محاضر صالحًا للإسناد أولًا.">إسناد المحاضر</Button></form></details>}
    <section className={styles.info}><strong>الشهادة</strong><p>{enrollment.certificate?.status==='issued'?`الشهادة ${enrollment.certificate.number} صدرت بالفعل.`:enrollment.eligibility?.eligible?'استوفى المتدرب شروط الإصدار.':(enrollment.eligibility?.reasons||[]).map(label).join(' · ')||'يُراجع الاستحقاق بعد استكمال متطلبات الدورة.'}</p><div className={styles.actions}><Button disabled={busy||!enrollment.eligibility?.eligible||enrollment.certificate?.status==='issued'} reason="يجب استيفاء شروط التعلم والحضور والتقييم والتسوية المالية أولًا." onClick={()=>void mutate('issue_certificate',{enrollmentId:enrollment.id},'تم إصدار الشهادة وربطها بسجل المتدرب.')}>إصدار الشهادة</Button></div></section>
  </div>;
}

function LearningSpace({enrollments,courses,busy,mutate}:{enrollments:TrainingEnrollment[];courses:TrainingCourse[];busy:boolean;mutate:TrainingMutation}){
  const [selected,setSelected]=useState(enrollments[0]?.id||'');
  const enrollment=enrollments.find(item=>item.id===selected)||enrollments[0];
  return <Panel title="مساحة التعلم" description="ابدأ بالأنشطة المطلوبة، ثم تابع نتيجتك وملاحظات المحاضر.">{!enrollment?<Empty title="رحلتك التدريبية ستبدأ هنا">تظهر الدورة بعد اكتمال التسجيل وإسناد المحتوى.</Empty>:<><Field label="الدورة"><select value={enrollment.id} onChange={event=>setSelected(event.target.value)}>{enrollments.map(item=><option key={item.id} value={item.id}>{item.courseTitle} · {item.runTitle||'تعلم ذاتي'}</option>)}</select></Field><LearnerCourse key={enrollment.id} enrollment={enrollment} course={courses.find(item=>item.id===enrollment.courseId)} busy={busy} mutate={mutate}/></>}</Panel>;
}
function LearnerCourse({enrollment,course,busy,mutate}:{enrollment:TrainingEnrollment;course?:TrainingCourse;busy:boolean;mutate:TrainingMutation}){
  const [opened,setOpened]=useState<TrainingUnit|null>(null);
  const units=enrollment.units||course?.versions.find(item=>item.id===enrollment.versionId)?.units||[];
  const allowed=enrollment.financialAccess?.trainingAllowed===true;
  const sessions=enrollment.sessions||[];
  async function openUnit(unitId:string){setOpened(null);const result=await mutate('open_unit',{enrollmentId:enrollment.id,unitId},'تم فتح النشاط.');if(result?.unit&&typeof result.unit==='object')setOpened(result.unit as TrainingUnit);}
  return <div className={styles.stack}><Progress percent={enrollment.progress?.percent||0}/><div className={styles.row}><strong>{enrollment.courseTitle}</strong><span>{number(enrollment.progress?.completedUnits)} / {number(enrollment.progress?.totalUnits)} نشاط</span></div>{!allowed&&<div className={styles.info}><strong>دخول المحتوى بانتظار استيفاء السداد</strong><p>{reasonList(enrollment.financialAccess)||'تواصل مع القبول أو الحسابات لمتابعة تسجيلك. تقدمك ونتائجك محفوظان.'}</p></div>}
    {!units.length?<Empty title="المحتوى قيد التجهيز">سيظهر تسلسل الدروس بعد إسناد إصدار منشور لتسجيلك.</Empty>:<div className={styles.split}><aside className={styles.unitList} aria-label="أنشطة الدورة">{units.map((unit,index)=><button type="button" key={unit.id} className={styles.unit} aria-current={opened?.id===unit.id} disabled={busy||(!allowed&&!unit.completedAt)} data-block-reason={!allowed&&!unit.completedAt?'يُفتح النشاط بعد استيفاء شروط السداد.':undefined} onClick={()=>void openUnit(unit.id)}><strong>{number(index+1)}. {unit.title}</strong><small>{TRAINING_UNIT_LABELS[unit.kind]} · {unit.completedAt?'مكتمل':unit.required?'مطلوب':'إثرائي'}</small></button>)}</aside><section className={styles.card}>{opened&&(allowed||units.some(unit=>unit.id===opened.id&&unit.completedAt))?<UnitActivity key={opened.id} unit={opened} enrollmentId={enrollment.id} busy={busy} mutate={mutate}/>:<Empty title={allowed?'اختر نشاطًا للبدء':'تقدمك محفوظ'}>{allowed?'كل نشاط يوضح المطلوب منك، ونتيجتك تظهر بعد التسليم أو التصحيح.':'يمكنك مراجعة تقدمك والشهادات والطلبات أثناء متابعة السداد.'}</Empty>}</section></div>}
    {!!sessions.length&&<section className={styles.card}><h3>اللقاءات المباشرة</h3><div className={styles.stack}>{sessions.map(session=>{const url=allowed?safeTrainingExternalUrl(session.joinUrl):null;return <div key={session.id} className={styles.row}><div><strong>{session.title}</strong><p>{date(session.startsAt)}</p></div>{url?<a className={styles.button} href={url} target="_blank" rel="noopener noreferrer">الدخول للقاء</a>:<Badge value={session.status||'موعد مسجل'}/>}</div>;})}</div></section>}
    {enrollment.policy?.supportEmail&&<p className={styles.secondaryText}>الدعم التعليمي: <a href={`mailto:${encodeURIComponent(enrollment.policy.supportEmail)}`}>{enrollment.policy.supportEmail}</a></p>}
  </div>;
}
function UnitActivity({unit,enrollmentId,busy,mutate}:{unit:TrainingUnit;enrollmentId:string;busy:boolean;mutate:TrainingMutation}){
  const [answers,setAnswers]=useState<Record<string,number>>({});
  const [assignment,setAssignment]=useState('');
  const [result,setResult]=useState<{score?:number;passed?:boolean;attempt?:number}|null>(null);
  const url=safeTrainingExternalUrl(unit.url);
  const questions=unit.questions||[];
  return <div className={styles.form}><div className={styles.row}><h3>{unit.title}</h3><Badge value={TRAINING_UNIT_LABELS[unit.kind]}/></div>{unit.body&&<div className={styles.content}>{unit.body}</div>}{url&&<a className={styles.button} href={url} target="_blank" rel="noopener noreferrer">فتح {unit.kind==='video'?'الفيديو':'المصدر'} في نافذة جديدة</a>}
    {unit.kind==='quiz'?<form className={styles.form} onSubmit={async event=>{event.preventDefault();const response=await mutate('submit_quiz',{enrollmentId,unitId:unit.id,answers},'تم تصحيح الاختبار وتسجيل النتيجة.');if(response)setResult(response);}}>{questions.map((question,index)=><fieldset className={styles.question} key={question.id}><legend>{number(index+1)}. {question.prompt}</legend>{question.options.map((option,optionIndex)=><label key={optionIndex}><input type="radio" name={`question-${unit.id}-${question.id}`} value={optionIndex} checked={answers[question.id]===optionIndex} onChange={()=>setAnswers({...answers,[question.id]:optionIndex})} required/>{option}</label>)}</fieldset>)}{result&&<div className={styles.info}><strong>النتيجة: {number(result.score)}٪ · {result.passed?'اجتزت الاختبار':'تحتاج محاولة أخرى'}</strong>{result.attempt&&<p>المحاولة {number(result.attempt)}</p>}</div>}<p className={styles.secondaryText}>درجة الاجتياز {number(unit.passPercent)}٪ · الحد الأقصى {number(unit.maxAttempts)} محاولات</p><div><Button type="submit" primary disabled={busy||!questions.length||Object.keys(answers).length!==questions.length} reason="أجب عن جميع الأسئلة قبل التسليم.">تسليم الاختبار</Button></div></form>:unit.kind==='assignment'?<form className={styles.form} onSubmit={event=>{event.preventDefault();void mutate('submit_assignment',{enrollmentId,unitId:unit.id,body:assignment.trim()},'تم تسليم الواجب للمحاضر. ستظهر النتيجة بعد التصحيح.');}}><Field label="إجابتك على الواجب"><textarea value={assignment} onChange={event=>setAssignment(event.target.value)} minLength={10} maxLength={20000} required/></Field><div><Button type="submit" primary disabled={busy}>تسليم الواجب</Button></div></form>:<><p className={styles.secondaryText}>{unit.minimumSeconds>0?`الوقت المطلوب لهذا النشاط: ${number(unit.minimumSeconds)} ثانية. يتحقق النظام من الوقت قبل اعتماد الإكمال.`:'بعد الاطلاع على النشاط يمكنك تسجيل إكماله.'}</p><div><Button primary disabled={busy} onClick={()=>void mutate('complete_unit',{enrollmentId,unitId:unit.id},'تم حفظ إكمال النشاط وتحديث تقدمك.')}>أكملت النشاط</Button></div></>}
  </div>;
}
function Grading({submissions,busy,mutate}:{submissions:TrainingSubmission[];busy:boolean;mutate:TrainingMutation}){return <Panel title="تصحيح الواجبات" description="الدرجات والملاحظات ترتبط بالتسليم الفعلي وتظهر للمتدرب بعد الحفظ.">{!submissions.length?<Empty title="لا توجد واجبات للتصحيح بعد">تظهر هنا التسليمات المرتبطة بالدفعات المتاحة لحسابك.</Empty>:<div className={styles.stack}>{submissions.map(submission=><GradeCard key={submission.id} submission={submission} busy={busy} mutate={mutate}/>)}</div>}</Panel>;}
function GradeCard({submission,busy,mutate}:{submission:TrainingSubmission;busy:boolean;mutate:TrainingMutation}){
  const [score,setScore]=useState(submission.grade?.score==null?'':String(submission.grade.score));
  const [feedback,setFeedback]=useState(submission.grade?.feedback||'');
  return <article className={styles.card}><div className={styles.row}><div><h3>{submission.studentName||'تسليم المتدرب'}</h3><p>{submission.unitTitle} · {date(submission.submittedAt)}</p></div><Badge value={submission.grade?'تم التصحيح':'بانتظار التصحيح'} good={Boolean(submission.grade)}/></div><div className={styles.content}>{submission.body}</div><form className={styles.form} onSubmit={event=>{event.preventDefault();void mutate('grade_assignment',{submissionId:submission.id,score:Number(score),feedback:feedback.trim()},'تم حفظ الدرجة والملاحظات.');}}><Field label="الدرجة من ١٠٠"><input type="number" min={0} max={100} step="0.01" value={score} onChange={event=>setScore(event.target.value)} required/></Field><Field label="ملاحظات للمتدرب"><textarea value={feedback} onChange={event=>setFeedback(event.target.value)} maxLength={4000} required minLength={3}/></Field><div><Button primary type="submit" disabled={busy}>حفظ التقييم</Button></div></form></article>;
}
function Attendance({enrollments,busy,mutate}:{enrollments:TrainingEnrollment[];busy:boolean;mutate:TrainingMutation}){
  const [enrollmentId,setEnrollmentId]=useState(enrollments[0]?.id||'');
  const enrollment=enrollments.find(item=>item.id===enrollmentId)||enrollments[0];
  return <Panel title="حضور اللقاءات" description="الحضور مرتبط بمتدرب وجلسة محددين، وتُحفظ أسباب التعديل.">{!enrollment?<Empty title="لا توجد تسجيلات للحضور">تظهر تسجيلات الدفعات المسندة إليك بعد القبول.</Empty>:<><Field label="المتدرب والدورة"><select value={enrollment.id} onChange={event=>setEnrollmentId(event.target.value)}>{enrollments.map(item=><option key={item.id} value={item.id}>{item.studentName} · {item.courseTitle} · {item.runTitle}</option>)}</select></Field><AttendanceForm key={enrollment.id} enrollment={enrollment} busy={busy} mutate={mutate}/></>}</Panel>;
}
function AttendanceForm({enrollment,busy,mutate}:{enrollment:TrainingEnrollment;busy:boolean;mutate:TrainingMutation}){
  const [sessionId,setSessionId]=useState('');const [status,setStatus]=useState('present');const [minutes,setMinutes]=useState('5');const [reason,setReason]=useState('');
  const sessions=(enrollment.sessions||[]).filter(item=>item.status!=='cancelled');
  return !sessions.length?<Empty title="لا توجد لقاءات مجدولة">التعلم الذاتي يتابع إكمال المحتوى، واللقاءات تظهر بعد إضافتها لجدول الدفعة.</Empty>:<form className={styles.form} onSubmit={event=>{event.preventDefault();void mutate('record_attendance',{enrollmentId:enrollment.id,sessionId,status,minutesLate:status==='late'?Number(minutes):0,reason:reason.trim()},'تم تسجيل الحضور وحفظ سبب الإجراء.');}}><div className={styles.formGrid}><Field label="اللقاء"><select value={sessionId} onChange={event=>setSessionId(event.target.value)} required><option value="">اختر اللقاء</option>{sessions.map(item=><option key={item.id} value={item.id}>{item.title} · {date(item.startsAt)}</option>)}</select></Field><Field label="حالة الحضور"><select value={status} onChange={event=>setStatus(event.target.value)}><option value="present">حاضر</option><option value="absent">غائب</option><option value="late">متأخر</option><option value="excused">بعذر</option></select></Field>{status==='late'&&<Field label="دقائق التأخير"><input type="number" min={1} max={1440} required value={minutes} onChange={event=>setMinutes(event.target.value)}/></Field>}</div><Field label="سبب الإجراء أو مصدر إثبات الحضور"><textarea value={reason} onChange={event=>setReason(event.target.value)} minLength={3} maxLength={2000} required/></Field><div><Button primary type="submit" disabled={busy}>حفظ الحضور</Button></div></form>;
}

function RequestWorkspace({data,busy,mutate}:{data:TrainingJourneySnapshot;busy:boolean;mutate:TrainingMutation}){
  const manager=data.role==='manager';
  const enrollments=data.learning?.enrollments||[];
  const requests=manager?data.operations?.requests||[]:data.learning?.requests||[];
  const [enrollmentId,setEnrollmentId]=useState('');const [kind,setKind]=useState<'transfer'|'defer'|'withdraw'|'access_exception'|'resume'>('transfer');
  const [reason,setReason]=useState('');const [targetRunId,setTargetRunId]=useState('');const [staffId,setStaffId]=useState('');const [dueAt,setDueAt]=useState('');
  const enrollment=enrollments.find(item=>item.id===enrollmentId);
  const runs=(manager?data.operations?.runs||[]:data.learning?.availableRuns||[]).filter(item=>item.courseId===enrollment?.courseId&&item.id!==enrollment?.runId);
  const certificates=enrollments.filter(item=>item.certificate?.status==='issued');
  return <><Panel title="طلبات المتدربين" description="النقل والتأجيل والانسحاب تُراجع مع الحفاظ على التسجيل الأصلي وسجل التعلم.">
    {(!manager||data.operations?.capabilities.canManage)&&<details className={styles.details}><summary>طلب جديد</summary><form className={styles.form} onSubmit={async event=>{event.preventDefault();const result=await mutate('create_request',{enrollmentId,kind,reason:reason.trim(),...(targetRunId?{targetRunId}:{}),...(manager?{assignedStaffId:staffId,dueAt:tenantDateTimeToISO(dueAt,data.tenant.timezone||'Asia/Riyadh')}:{})},'تم تسجيل الطلب وإسناده للمراجعة.');if(result){setReason('');setTargetRunId('');}}}><div className={styles.formGrid}><Field label="التسجيل"><select value={enrollmentId} onChange={event=>{setEnrollmentId(event.target.value);setTargetRunId('');}} required><option value="">اختر التسجيل</option>{enrollments.map(item=><option key={item.id} value={item.id}>{manager?`${item.studentName} · `:''}{item.courseTitle} · {item.runTitle||'تعلم ذاتي'}</option>)}</select></Field><Field label="نوع الطلب"><select value={kind} onChange={event=>{setKind(event.target.value as typeof kind);setTargetRunId('');}}>{Object.entries(REQUEST_LABELS).filter(([key])=>manager||key!=='access_exception').map(([key,title])=><option key={key} value={key}>{title}</option>)}</select></Field>{['transfer','defer'].includes(kind)&&<Field label="الدفعة المطلوبة"><select value={targetRunId} onChange={event=>setTargetRunId(event.target.value)} required={kind==='transfer'}><option value="">{kind==='transfer'?'اختر الدفعة':'تحددها إدارة القبول'}</option>{runs.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></Field>}{manager&&<><Field label="الموظف المسؤول"><select value={staffId} onChange={event=>setStaffId(event.target.value)} required><option value="">اختر المسؤول</option>{(data.operations?.staff||[]).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="موعد الإنجاز" hint={`بتوقيت المنشأة: ${data.tenant.timezone||'Asia/Riyadh'}`}><input type="datetime-local" value={dueAt} onChange={event=>setDueAt(event.target.value)} required/></Field></>}</div><Field label="سبب الطلب"><textarea value={reason} onChange={event=>setReason(event.target.value)} required minLength={5} maxLength={2000}/></Field><div><Button primary type="submit" disabled={busy||!enrollments.length} reason="يلزم تسجيل تدريبي قائم لإنشاء الطلب.">إرسال للمراجعة</Button></div></form></details>}
    {!requests.length?<Empty title="لا توجد طلبات مسجلة">يمكن إنشاء طلب مرتبط بالتسجيل، ومتابعة قراره هنا.</Empty>:<div className={styles.stack}>{requests.map(request=><RequestCard key={request.id} request={request} data={data} busy={busy} mutate={mutate}/>)}</div>}
  </Panel>{data.role==='learner'&&<Panel title="شهاداتي" description="تظهر الشهادات بعد إتمام الشروط واعتماد الإصدار.">{!certificates.length?<Empty title="شهاداتك ستظهر هنا">تابع المتطلبات المتبقية في دورتك حتى استحقاق الشهادة.</Empty>:<div className={styles.grid}>{certificates.map(item=><article key={item.id} className={styles.card}><Badge value="صدرت الشهادة" good/><h3>{item.courseTitle}</h3><p>رقم الشهادة: {item.certificate?.number}</p><p>تاريخ الإصدار: {date(item.certificate?.issuedAt,data.tenant.timezone)}</p>{item.certificate?.verificationCode&&<p>رمز التحقق: <bdi>{item.certificate.verificationCode}</bdi></p>}</article>)}</div>}</Panel>}</>;
}
function RequestCard({request,data,busy,mutate}:{request:NonNullable<TrainingOperationsSnapshot['requests']>[number];data:TrainingJourneySnapshot;busy:boolean;mutate:TrainingMutation}){
  const [decision,setDecision]=useState('approve');const [reason,setReason]=useState('');const [exceptionUntil,setExceptionUntil]=useState('');
  const enrollment=data.learning?.enrollments.find(item=>item.id===request.enrollmentId);
  const staff=data.operations?.staff.find(item=>item.id===request.assignedStaffId);
  return <article className={styles.card}><div className={styles.row}><div><h3>{REQUEST_LABELS[request.kind]}</h3><p>{enrollment?.studentName} · {enrollment?.courseTitle}</p></div><Badge value={request.status}/></div><p>{request.reason}</p>{data.role==='manager'&&<p>المسؤول: {staff?.name||'الموظف المسند'} · الموعد: {date(request.dueAt,data.tenant.timezone)}</p>}{data.role==='manager'&&data.operations?.capabilities.canManage&&['pending','requested','in_review','open'].includes(request.status)&&<details className={styles.details}><summary>مراجعة الطلب واتخاذ القرار</summary><form className={styles.form} onSubmit={event=>{event.preventDefault();void mutate('decide_request',{requestId:request.id,decision,reason:reason.trim(),...(request.kind==='access_exception'&&decision==='approve'?{exceptionUntil:tenantDateTimeToISO(exceptionUntil,data.tenant.timezone||'Asia/Riyadh')}:{})},'تم حفظ القرار وتحديث التسجيل والمهام المرتبطة.');}}><Field label="القرار"><select value={decision} onChange={event=>setDecision(event.target.value)}><option value="approve">موافقة</option><option value="reject">رفض</option></select></Field>{request.kind==='access_exception'&&decision==='approve'&&<Field label="نهاية الاستثناء" hint={`بتوقيت ${data.tenant.timezone||'Asia/Riyadh'}`}><input type="datetime-local" value={exceptionUntil} onChange={event=>setExceptionUntil(event.target.value)} required/></Field>}<Field label="مبرر القرار"><textarea value={reason} onChange={event=>setReason(event.target.value)} required minLength={5} maxLength={2000}/></Field><div><Button primary type="submit" disabled={busy}>اعتماد القرار</Button></div></form></details>}</article>;
}
function tenantDateTimeToISO(value:string,timezone:string){
  const parts=value.match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})$/);if(!parts)return '';
  const input=Date.UTC(Number(parts[1]),Number(parts[2])-1,Number(parts[3]),Number(parts[4]),Number(parts[5]));let result=input;
  for(let i=0;i<2;i++){const formatted=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date(result));const p=Object.fromEntries(formatted.map(part=>[part.type,part.value]));const actual=Date.UTC(Number(p.year),Number(p.month)-1,Number(p.day),Number(p.hour),Number(p.minute),Number(p.second));result+=input-actual;}
  return new Date(result).toISOString();
}
function TaskWorkspace({operations,slug,timezone,busy,mutate}:{operations?:TrainingOperationsSnapshot|null;slug:string;timezone?:string;busy:boolean;mutate:TrainingMutation}){
  return <><Panel title="مهام التشغيل" description="المهمة مرتبطة بالخطوة المتعثرة. إتمام الإجراء الصحيح يغلق الحلقة ويحفظ أثره." actions={<Link className={styles.button} href={`/tenant/${encodeURIComponent(slug)}/tasks`}>تقويم مهام أودير</Link>}>
    {!operations?.tasks.length?<Empty title="لا توجد مهام تدريبية معلقة">تظهر هنا الحالات التي تحتاج إسنادًا أو مراجعة أو تدخلًا من الموظف المسؤول.</Empty>:<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>المهمة</th><th>المسؤول</th><th>موعد الإنجاز</th><th>الحالة</th></tr></thead><tbody>{operations.tasks.map(task=><tr key={task.id}><td>{task.title}</td><td>{operations.staff.find(item=>item.id===task.assignedStaffId)?.name||'بانتظار الإسناد'}</td><td>{date(task.dueAt,timezone)}</td><td><Badge value={task.status}/></td></tr>)}</tbody></table></div>}
    {operations?.capabilities.canManage&&<div className={styles.actions}><Button disabled={busy} onClick={()=>void mutate('reconcile',{},'تمت مراجعة حالات التدريب والمهام المرتبطة.')}>مراجعة الحالات المعلقة</Button></div>}
  </Panel>{operations?.automation&&<AutomationSettings key={JSON.stringify(operations.automation)} initial={operations.automation} busy={busy} mutate={mutate}/>}</>;
}
function AutomationSettings({initial,busy,mutate}:{initial:NonNullable<TrainingOperationsSnapshot['automation']>;busy:boolean;mutate:TrainingMutation}){
  const [enabled,setEnabled]=useState(initial.enabled);const [admissions,setAdmissions]=useState(initial.admissionsStaffId||'');const [finance,setFinance]=useState(initial.financeStaffId||'');const [escalation,setEscalation]=useState(initial.escalationStaffId||'');const [assignmentDays,setAssignmentDays]=useState(initial.assignmentDueDays||1);const [gradingDays,setGradingDays]=useState(initial.gradingDueDays||2);const [preview,setPreview]=useState<TrainingMutationResult|null>(null);
  return <Panel title="المتابعة التلقائية" description="تسند الحالات المعلقة للموظف المناسب، وتتابع موعد الإنجاز والتصعيد."><form className={styles.form} onSubmit={event=>{event.preventDefault();void mutate('automation_settings',{enabled,admissionsStaffId:admissions||null,financeStaffId:finance||null,escalationStaffId:escalation||null,assignmentDueDays:assignmentDays,gradingDueDays:gradingDays},'تم حفظ إعدادات المتابعة التلقائية.');}}><label className={styles.check}><input type="checkbox" checked={enabled} onChange={event=>setEnabled(event.target.checked)}/>تفعيل المتابعة التلقائية لهذه المنشأة</label><div className={styles.formGrid}>{[['مسؤول القبول والإسناد',admissions,setAdmissions],['مسؤول متابعة السداد',finance,setFinance],['مسؤول التصعيد',escalation,setEscalation]].map(([title,value,setter])=><Field key={title as string} label={title as string}><select value={value as string} onChange={event=>(setter as (value:string)=>void)(event.target.value)} required={enabled}><option value="">اختر الموظف</option>{initial.staffCandidates.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field>)}<Field label="مهلة الإسناد بالأيام"><input type="number" value={assignmentDays} onChange={event=>setAssignmentDays(Number(event.target.value))} min={1} max={7} required/></Field><Field label="مهلة تصحيح الواجب بالأيام"><input type="number" value={gradingDays} onChange={event=>setGradingDays(Number(event.target.value))} min={1} max={14} required/></Field></div>{!initial.cronAvailable&&<p className={styles.info}>المراجعة التلقائية المجدولة لم تُجهز بعد؛ يمكنك استخدام مراجعة الحالات يدويًا.</p>}<div className={styles.actions}><Button type="submit" primary disabled={busy}>حفظ الإعدادات</Button><Button disabled={busy} onClick={async()=>setPreview(await mutate('automation_preview',{},'تمت معاينة الحالات دون إنشاء مهام.'))}>معاينة الحالات</Button></div></form>{preview&&<div className={styles.info} role="status">تم فحص {number(preview.checkedCount)} حالة · تحتاج إجراءً: {number(preview.actionableCount)} · تحتاج مسؤولًا: {number(preview.missingAssigneeCount)}</div>}</Panel>;
}
function Readiness({courses}:{courses:TrainingCourse[]}){const published=courses.flatMap(course=>course.versions.filter(version=>version.status==='published').map(version=>({course,version})));return <Panel title="جاهزية البرامج" description="راجع شروط كل إصدار منشور ومعلومات الدعم قبل إسناده للمتدربين.">{!published.length?<Empty title="لا توجد إصدارات منشورة">جهز المحتوى وشروط الإكمال وقنوات الدعم، ثم أكمل المراجعة البشرية والنشر.</Empty>:<div className={styles.stack}>{published.map(({course,version})=><article className={styles.card} key={version.id}><div className={styles.row}><h3>{course.title} · الإصدار {number(version.version)}</h3><Badge value={LEARNING_MODE_LABELS[version.learningMode]}/></div><dl className={styles.policy}><div><dt>الحضور المطلوب</dt><dd>{number(version.policy.minAttendancePercent)}٪</dd></div><div><dt>التقييم المطلوب</dt><dd>{number(version.policy.minAssessmentPercent)}٪</dd></div><div><dt>الشهادة</dt><dd>{version.policy.certificateEnabled?'متاحة عند استيفاء الشروط':'غير مفعلة'}</dd></div><div><dt>مرجع الشروط</dt><dd>{version.policy.termsVersion||'لم يحدد'}</dd></div><div><dt>بريد الدعم</dt><dd>{version.policy.supportEmail||'لم يحدد'}</dd></div><div><dt>دورة المحتوى</dt><dd>إصدار منشور بعد المراجعة</dd></div></dl></article>)}</div>}<p className={styles.secondaryText}>نسب الحضور والاجتياز هي سياسات البرنامج المسجلة. متابعة التراخيص والربط الرسمي تتم وفق متطلبات الجهة المنظمة للبرنامج.</p></Panel>;}
function LearnerResults({submissions}:{submissions:TrainingSubmission[]}){return <Panel title="نتائجي وملاحظات المحاضر" description="تسليماتك ونتائجها محفوظة حتى عند تأجيل التدريب أو تعليق الدخول.">{!submissions.length?<Empty title="لا توجد تسليمات بعد">بعد تسليم الواجب، تظهر حالته وملاحظات المحاضر هنا.</Empty>:<div className={styles.stack}>{submissions.map(item=><article className={styles.card} key={item.id}><div className={styles.row}><h3>{item.unitTitle}</h3><Badge value={item.grade?`${number(item.grade.score)} / ١٠٠`:'بانتظار التصحيح'} good={Boolean(item.grade)}/></div><p>التسليم: {date(item.submittedAt)}</p><details className={styles.details}><summary>عرض إجابتي</summary><div className={styles.content}>{item.body}</div></details>{item.grade?.feedback&&<div className={styles.info}><strong>ملاحظات المحاضر</strong><p>{item.grade.feedback}</p></div>}</article>)}</div>}</Panel>;}
