'use client';
import {useState} from 'react';
import styles from './zoom-workspace.module.css';
const Field=({label,children})=><label className={styles.field}><span>{label}</span>{children}</label>;

export function ZoomPoll({row,action,busy}){
 return <details className={styles.card}><summary>استطلاع داخل المحاضرة</summary><p>يتطلب تفعيل الاستطلاعات وصلاحياتها في حساب زووم. يُنشأ كطلب خلفي وتظهر أعطاله ضمن متابعة المحاضرة.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);action('poll',{linkId:row.linkId,expectedVersion:row.revision,title:f.get('title'),questions:[{name:f.get('question'),type:f.get('type'),answers:String(f.get('answers')).split('\n').map(x=>x.trim()).filter(Boolean)}]});}}><Field label="عنوان الاستطلاع"><input name="title" required maxLength={64}/></Field><Field label="السؤال"><input name="question" required maxLength={255}/></Field><Field label="نوع الإجابة"><select name="type"><option value="single">إجابة واحدة</option><option value="multiple">إجابات متعددة</option></select></Field><Field label="الاختيارات، كل اختيار في سطر"><textarea name="answers" rows={4} required maxLength={2500}/></Field><button disabled={busy}>إرسال طلب إنشاء الاستطلاع</button></form></details>;
}
export function ZoomWebinar({row,action,busy,slug}){
 const [data,setData]=useState(null),[registration,setRegistration]=useState(null);
 async function refresh(){const r=await action('webinar_snapshot',{linkId:row.linkId},'حُدّث سجل الندوة.');if(r)setData(r);}
 return <details className={styles.card}><summary>الندوة والمبيعات</summary><p>المسجل عميل في سجل المبيعات القائم. حضور الندوة لا يمنحه تسجيلًا دراسيًا ولا يمثل إيرادًا.</p><button disabled={busy} onClick={refresh}>تحميل سجل الندوة</button><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);action('webinar_configure',{linkId:row.linkId,source:f.get('source'),consentVersion:f.get('consentVersion'),campaignId:f.get('campaignId')||null});}}><Field label="مصدر التسجيل"><input name="source" required minLength={2} defaultValue={data?.campaign?.source||''}/></Field><Field label="نسخة نص موافقة التسجيل"><input name="consentVersion" required minLength={2} defaultValue={data?.campaign?.consent_version||''}/></Field><Field label="الحملة"><select name="campaignId" defaultValue={data?.campaign?.campaign_id||''}><option value="">دون حملة</option>{(data?.campaigns||[]).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><button disabled={busy}>حفظ ربط الندوة</button></form>
 {data?.campaign&&<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const r=await action('webinar_prepare',{linkId:row.linkId,name:f.get('name'),email:f.get('email'),phone:f.get('phone')||null,consentVersion:data.campaign.consent_version,registrationConsent:f.get('registrationConsent')==='on',marketingConsent:f.get('marketingConsent')==='on'},'حُفظ طلب التسجيل مع فحص تكرار العميل.');if(r)setRegistration(r.registrationId);}}><h3>تسجيل عميل بموافقته</h3><Field label="اسم العميل"><input name="name" required minLength={2}/></Field><Field label="البريد الذي وافق العميل على استخدامه"><input name="email" type="email" dir="ltr" required/></Field><Field label="الجوال"><input name="phone" type="tel" dir="ltr"/></Field><label><input type="checkbox" name="registrationConsent" required/> لدى المنشأة موافقته على التسجيل في هذه الندوة.</label><label><input type="checkbox" name="marketingConsent"/> وافق بشكل منفصل على المتابعة التسويقية.</label><button disabled={busy}>فحص العميل وتجهيز التسجيل</button></form>}
 {registration&&<button disabled={busy} onClick={async()=>{if(await action('webinar_register',{registrationId:registration},'تأكد تسجيل العميل لدى زووم.')){setRegistration(null);await refresh();}}}>تأكيد التسجيل لدى زووم</button>}
 <ul>{(data?.registrations||[]).map(r=><li key={r.id}>{r.full_name} · {r.state==='registered'?'مسجل لدى زووم':'لم يكتمل الربط'} · {r.attended_seconds==null?'الحضور غير متاح':`${Math.round(r.attended_seconds/60)} دقيقة`}</li>)}</ul><p>الإيراد يُقرأ من <a href={`/tenant/${slug}/reports/campaigns`}>تقرير الحملات القائم</a>؛ لا يُستنتج من الحضور.</p></details>;
}
export function ZoomRecordingAI({row,action,busy}){
 const [draft,setDraft]=useState(null),[context,setContext]=useState(null);
 async function load(){const ctx=await action('ai_snapshot',{recordingId:row.id},'حُمّلت المسودات المتاحة.');if(ctx){setContext(ctx);setDraft(ctx.drafts?.find(d=>d.state==='draft')||null);}}
 return <details className={styles.card}><summary>تفريغ ومسودة تعليمية</summary><p>التوليد يستهلك ميزانية أوديري بعد موافقة المنشأة. الناتج مسودة تحتاج مراجعة بشرية، مع بقاء الحضور والشهادات تحت قواعدها القائمة.</p><div className={styles.actions}><button disabled={busy} onClick={()=>action('transcript',{recordingId:row.id},'جُلب التفريغ المصرح به من المصدر.')}>جلب التفريغ</button><button disabled={busy} onClick={load}>المسودات المحفوظة</button></div><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const r=await action('ai_generate',{recordingId:row.id,sourceRevision:row.transcript_revision,kind:f.get('kind'),consent:f.get('consent')==='on'},'حُفظت مسودة مرتبطة بإصدار المصدر. راجعها قبل الاستخدام.');if(r){setDraft(r);const ctx=await action('ai_snapshot',{recordingId:row.id},'المسودة جاهزة للمراجعة.');setContext(ctx);}}}><Field label="نوع المسودة"><select name="kind"><option value="summary">ملخص تعليمي</option><option value="questions">أسئلة مراجعة</option><option value="unit">وحدة تعليمية</option></select></Field><label><input type="checkbox" name="consent" required/> أوافق على معالجة هذا التفريغ للغرض التعليمي المعتمد.</label><button disabled={busy||!row.transcript_revision}>توليد مسودة</button></form>
 {draft?.content&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);action('ai_apply',{draftId:draft.id,courseId:context?.courseId,expectedVersion:context?.authoringRevision,title:f.get('title'),body:f.get('body'),reviewed:f.get('reviewed')==='on'},'أُضيفت وحدة إلى مسودة المقرر في محرر أودير؛ لم تُنشر للطلاب.');}}><h3>مراجعة المسودة</h3><Field label="العنوان"><input name="title" defaultValue={draft.content.title} required maxLength={180}/></Field><Field label="المحتوى المراجع"><textarea name="body" rows={10} required defaultValue={[draft.content.summary,...(draft.content.points||[]),...(draft.content.questions||[]).map(q=>`${q.prompt}\n${q.options.join(' / ')}\n${q.explanation}`)].join('\n\n')}/></Field><p>المصدر: الإصدار {draft.sourceRevision||draft.source_revision} · النموذج: <span dir="ltr">{draft.model}</span></p><p>الوحدات المستهلكة: {draft.usage?.businessUnits??'تظهر في سجل أوديري'}</p><label><input name="reviewed" type="checkbox" required/> راجعت دقة المحتوى ومصادره.</label><button disabled={busy||context?.authoringRevision==null}>إضافة إلى مسودة المقرر</button>{context?.authoringRevision==null&&<p>تحتاج هذه الخطوة مقررًا مهيأً في محرر أودير وصلاحية LMS ضمن نطاق الطرح المعتمد.</p>}</form>}</details>;
}
