'use client';

import {useEffect,useState} from 'react';
import Link from 'next/link';
import {zoomErrorMessage} from '../lib/zoom-contract.mjs';
import styles from './zoom-workspace.module.css';

export async function zoomRequest(slug,action,payload={},commandId=crypto.randomUUID()){
 const response=await fetch(`/api/zoom/${action}`,{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'content-type':'application/json'},body:JSON.stringify({tenantSlug:slug,commandId,payload})});
 const result=await response.json();if(!response.ok)throw Error(result.error||zoomErrorMessage(result.code));return result;
}
const states={connected:'متصل',paused:'التوزيع متوقف',disconnected:'مفصول',reauth_required:'يحتاج إعادة ربط',deauthorized:'أُلغي التفويض',missing_scope:'صلاحيات ناقصة',queued:'بانتظار الإنشاء',updating:'جارٍ التعديل',cancelling:'جارٍ الإلغاء',ready:'جاهزة',imported:'مستوردة',live:'قائمة الآن',ended:'انتهت',cancelled:'ملغاة',uncertain:'النتيجة تحتاج تحققًا',drift:'تغيير يحتاج مراجعة',failed:'تحتاج معالجة',processing:'جارٍ تجهيز التسجيل',review:'بانتظار المراجعة',published:'متاح',withdrawn:'أُوقفت الإتاحة',deleted:'حُذفت النسخة المحلية'};
const date=value=>value?new Date(value).toLocaleString('ar-SA',{dateStyle:'medium',timeStyle:'short'}):'—';
const local=value=>{const d=new Date(value);return Number.isNaN(d.valueOf())?'':new Date(d.valueOf()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
const asDate=value=>value?new Date(value).toISOString():undefined;
function Field({label,children}){return <label className={styles.field}><span>{label}</span>{children}</label>;}
function Empty({children}){return <p className={styles.empty}>{children}</p>;}

export default function ZoomWorkspace({slug,initialData=null,initialView='sessions',sessionId=null,compact=false}){
 const [data,setData]=useState(initialData),[view,setView]=useState(initialView),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[offset,setOffset]=useState(0),[selected,setSelected]=useState(null),[candidates,setCandidates]=useState(null),[details,setDetails]=useState(null);
 const options={view,query,offset,...(sessionId?{sessionId}:{})};
 useEffect(()=>{let live=true;zoomRequest(slug,'snapshot',{view,query,offset,...(sessionId?{sessionId}:{})}).then(result=>{if(live){setData(result);setError('');}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[slug,view,query,offset,sessionId]);
 async function action(name,payload={},success='تم حفظ الطلب. تظهر النتيجة بعد تأكيد التنفيذ.'){
  if(busy)return null;setBusy(true);setError('');setNotice('');
  try{const result=await zoomRequest(slug,name,payload);if(result.authorizeUrl){window.location.assign(result.authorizeUrl);return result;}setNotice(success);setData(await zoomRequest(slug,'snapshot',options));if(details)setDetails({...details,data:await zoomRequest(slug,'snapshot',{view:details.view,linkId:details.row.linkId})});return result;}
  catch(e){setError(e.message);return null;}finally{setBusy(false);}
 }
 async function submitSession(event){event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));const payload={...values,sessionId:selected.id,expectedVersion:selected.revision,startsAt:asDate(values.startsAt),endsAt:asDate(values.endsAt),attendees:Number(values.attendees)};if(!payload.hostId)delete payload.hostId;
  const kind=event.nativeEvent.submitter?.value||'preview';if(kind==='preview'){const result=await action('preview',payload,'تم فحص الموارد المتاحة وقت الطلب. يُعاد الفحص عند الحفظ.');setCandidates(result?.candidates||[]);}else if(await action(kind,payload))setSelected(null);
 }
 async function openDetails(row,nextView){setSelected(null);try{setDetails({row,view:nextView,data:await zoomRequest(slug,'snapshot',{view:nextView,linkId:row.linkId})});}catch(e){setError(e.message);}}
 const permissions=data?.permissions||{},tabs=[['sessions','المحاضرات'],...(permissions.accounts?[['accounts','الحسابات والمضيفون']]:[]),...(permissions.sessions?[['reports','التقارير']]:[]),['recordings','التسجيلات']];
 return <section className={styles.workspace} dir="rtl" aria-label="تشغيل زووم">
  <header className={styles.header}><div><p className={styles.eyebrow}>أودير · التدريب المباشر</p><h1>{compact?'المحاضرة المباشرة':'تشغيل زووم'}</h1><p>الحسابات والمواعيد والحضور مرتبطة بسجل التدريب في المنشأة.</p></div>{!compact&&<Link href={`/tenant/${slug}/learners`}>العودة لتشغيل المتدربين</Link>}</header>
  {error&&<p className={styles.error} role="alert">{error}</p>}{notice&&<p className={styles.notice} role="status">{notice}</p>}
  {data&&!data.enabled&&<p className={styles.notice}>إضافة زووم غير مفعّلة. تفعيلها مستقل عن منصة التعلم.</p>}
  {!compact&&<nav className={styles.tabs} aria-label="أقسام زووم">{tabs.map(([key,label])=><button type="button" key={key} aria-current={view===key?'page':undefined} onClick={()=>{setView(key);setOffset(0);setSelected(null);setDetails(null);}}>{label}</button>)}</nav>}
  {!data&&!error&&<p role="status">جارٍ تحميل البيانات…</p>}
  {data&&<><div className={styles.toolbar}><Field label="بحث"><input value={query} onChange={e=>{setQuery(e.target.value);setOffset(0);}} placeholder="اسم المحاضرة أو المضيف" maxLength={100}/></Field><button disabled={busy} onClick={()=>action('snapshot',options,'حُدّثت البيانات.')}>تحديث الحالة</button></div>
  {view==='accounts'&&<>
   <div className={styles.toolbar}><h2>حسابات زووم</h2><button disabled={busy||!data.enabled} onClick={()=>action('connect',{mode:'add'})}>إضافة حساب</button></div>
   <div className={styles.cards}>{(data.accounts||[]).map(c=><article key={c.id} className={styles.card}><h3>{c.label}</h3><p>{states[c.status]||c.status}</p><small>آخر مزامنة: {date(c.last_synced_at)} · {c.sync_coverage==='complete'?'تغطية كاملة':'قد تكون الموارد الظاهرة جزئية'}</small><div className={styles.actions}><button disabled={busy} onClick={()=>action('sync_hosts',{connectionId:c.id},'اكتملت مزامنة الموارد التي تسمح بها صلاحيات الحساب.')}>مزامنة الموارد</button><button disabled={busy} onClick={()=>action('connect',{mode:'reconnect',connectionId:c.id})}>إعادة ربط</button><button disabled={busy} onClick={()=>action(c.status==='paused'?'resume':'pause',{connectionId:c.id,expectedVersion:c.generation})}>{c.status==='paused'?'استئناف التوزيع':'إيقاف التوزيع'}</button><button disabled={busy} onClick={()=>setSelected({...c,disconnect:true})}>فصل الحساب…</button></div></article>)}</div>
   {!data.accounts?.length&&<Empty>لم يُربط حساب حتى الآن. إضافة حساب آخر تُبقي الحسابات الحالية.</Empty>}
   {selected?.disconnect&&<form className={styles.card} onSubmit={async e=>{e.preventDefault();if(await action('disconnect',{connectionId:selected.id,expectedVersion:selected.generation}))setSelected(null);}}><h3>فصل {selected.label}</h3><p>يتوقف الوصول عبر هذا الاتصال وتحتاج المحاضرات المقبلة إلى معالجة. يبقى السجل الأكاديمي لدى أودير.</p><button disabled={busy}>تأكيد الفصل</button><button type="button" onClick={()=>setSelected(null)}>رجوع</button></form>}
   <h2>المضيفون</h2><div className={styles.cards}>{(data.hosts||[]).map(h=><form className={styles.card} key={`${h.id}:${h.revision}`} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);action('configure_host',{hostId:h.id,expectedVersion:h.revision,allowed:f.get('allowed')==='on',instructorId:f.get('instructorId')||null,beforeMinutes:Number(f.get('before')),afterMinutes:Number(f.get('after')),concurrency:Number(f.get('concurrency'))});}}><h3>{h.name}</h3><p>السعة: {h.capacity??'لم تُثبت'} · الخانات المثبتة: {h.provider_concurrency}</p><label><input name="allowed" type="checkbox" defaultChecked={h.allowed}/> السماح بالتوزيع</label><Field label="المدرب المرتبط"><select name="instructorId" defaultValue={h.instructor_subject_id||''}><option value="">اختر مدربًا</option>{(data.instructors||[]).map(i=><option value={i.id} key={i.id}>{i.full_name}</option>)}</select></Field><div className={styles.fields}><Field label="قبل المحاضرة بالدقائق"><input name="before" type="number" min="0" max="120" defaultValue={h.before_minutes}/></Field><Field label="بعدها بالدقائق"><input name="after" type="number" min="0" max="120" defaultValue={h.after_minutes}/></Field><Field label="الخانات المستخدمة"><input name="concurrency" type="number" min="1" max={h.provider_concurrency} defaultValue={h.concurrency_limit}/></Field></div><div className={styles.actions}><button disabled={busy}>حفظ</button><button type="button" disabled={busy||!h.instructor_subject_id} onClick={()=>action('verify_host',{hostId:h.id,instructorId:h.instructor_subject_id},'تحققت هوية المدرب لدى زووم.')}>التحقق من تفويض المدرب</button></div><small>اختيار اسم المدرب يحتاج تحققًا من هويته لدى زووم قبل الجدولة.</small></form>)}</div>
   {permissions.retention&&data.settings&&<form className={styles.card} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);action('settings',{expectedVersion:data.settings.revision,recordingPolicy:f.get('recording'),retentionDays:Number(f.get('days')),retentionApproved:f.get('approved')==='on',providerLimitAcknowledged:f.get('ack')==='on'});}}><h2>سياسة التسجيل</h2><div className={styles.fields}><Field label="التسجيل"><select name="recording" defaultValue={data.settings.recording_policy}><option value="off">متوقف</option><option value="manual">بقرار يدوي</option><option value="cloud">سحابي بعد موافقة المنشأة</option></select></Field><Field label="مدة الإتاحة بالأيام"><input name="days" type="number" min="1" max="3650" required defaultValue={data.settings.retention_policy?.days||''}/></Field></div><label><input name="approved" type="checkbox" required/> أعتمد سياسة الاحتفاظ والإتاحة للمنشأة.</label><label><input name="ack" type="checkbox" required/> أفهم أن إيقاف الرابط في أودير لا يمحو رابطًا سبق نسخه من زووم؛ تضبط الحماية كذلك في حساب زووم.</label><button disabled={busy}>حفظ السياسة</button></form>}
  </>}
  {view==='sessions'&&<><div className={styles.cards}>{(data.sessions||[]).map(s=><article key={s.id} className={styles.card}><small>{s.courseTitle} · {s.runTitle}</small><h2>{s.title}</h2><p>{date(s.startsAt)} — {date(s.endsAt)}</p><p>{states[s.state]||'لم يُربط اجتماع'} · {s.instructor||'المدرب يحدد عند الجدولة'}</p><div className={styles.actions}>{permissions.sessions&&<button disabled={busy||['queued','updating','cancelling','live','uncertain'].includes(s.state)} onClick={()=>{setSelected(s);setCandidates(null);setDetails(null);}}>{s.linkId?'تعديل أو معالجة':'توزيع المحاضرة'}</button>}{s.linkId&&<><Link href={`/training/${slug}/sessions/${s.id}?role=instructor`}>صفحة المحاضرة</Link><button disabled={busy} onClick={()=>openDetails(s,'attendance')}>أدلة الحضور</button><button disabled={busy} onClick={()=>openDetails(s,'recordings')}>التسجيلات</button><button disabled={busy} onClick={()=>action('reconcile',{sessionId:s.id,expectedVersion:s.revision})}>طلب مزامنة الأدلة</button></>}</div><small>آخر تحقق: {date(s.lastSyncedAt)}</small></article>)}</div>{!data.sessions?.length&&<Empty>لا توجد محاضرات ضمن الفترة الحالية. تُنشأ المحاضرات من جدول الدفعة القائم.</Empty>}
  {selected?.startsAt&&<form className={styles.card} onSubmit={submitSession}><h2>{selected.title}</h2><div className={styles.fields}><Field label="البداية بتوقيت جهازك"><input name="startsAt" type="datetime-local" required defaultValue={local(selected.startsAt)}/></Field><Field label="النهاية بتوقيت جهازك"><input name="endsAt" type="datetime-local" required defaultValue={local(selected.endsAt)}/></Field><Field label="المدرب"><select name="instructorId" required><option value="">اختر المدرب المعين للدفعة</option>{(data.instructors||[]).filter(i=>i.run_id===selected.runId).map(i=><option key={i.id} value={i.id}>{i.full_name}</option>)}</select></Field><Field label="المضيف"><select name="hostId"><option value="">توزيع تلقائي</option>{(data.hosts||[]).map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select></Field><Field label="العدد المتوقع"><input name="attendees" type="number" min="1" max="100000" required defaultValue="1"/></Field><Field label="نوع النشاط"><select name="kind"><option value="meeting">اجتماع تدريبي</option><option value="webinar">ندوة بترخيص زووم</option></select></Field><Field label="التسجيل"><select name="recording"><option value="off">متوقف</option><option value="cloud">سحابي وفق السياسة</option></select></Field></div><div className={styles.actions}><button value="preview" disabled={busy}>فحص الموارد</button><button value={selected.linkId?'update':'assign'} disabled={busy}>{selected.linkId?'حفظ التعديل':'حجز وإنشاء'}</button><button type="button" onClick={()=>setSelected(null)}>رجوع</button></div>{candidates&&<p role="status">الموارد المؤهلة الآن: {candidates.length}. {candidates.length?'التوزيع يفضل المدرب المرتبط ثم أقل الموارد انشغالًا.':'راجع التوقيت والتفويض والسعة.'}</p>}{selected.linkId&&<div className={styles.fields}><Field label="سبب الإلغاء"><input name="reason" minLength={5}/></Field><button type="button" disabled={busy} onClick={e=>action('cancel',{sessionId:selected.id,expectedVersion:selected.revision,reason:new FormData(e.currentTarget.form).get('reason')})}>إلغاء المحاضرة</button></div>}</form>}
  </>}
  {(view==='recordings'||details?.view==='recordings')&&<RecordingList rows={details?.data.recordings||data.recordings||[]} canPublish={permissions.recordings} busy={busy} action={action}/>}
  {details?.view==='attendance'&&<AttendanceReview details={details} busy={busy} action={action}/>}
  {view==='reports'&&<><h2>التشغيل في الفترة المحددة</h2><p>من {date(data.period?.from)} إلى {date(data.period?.to)}</p><div className={styles.cards}>{Object.entries({scheduled:'المحاضرات المرتبطة',ended:'المنتهية',cancelled:'الملغاة',exceptions:'تحتاج معالجة',evidenceComplete:'أدلتها مكتملة'}).map(([key,label])=><article className={styles.card} key={key}><span>{label}</span><strong>{data.summary?.[key]??'—'}</strong></article>)}</div><p>التكلفة: {data.cost==null?'غير متاحة من مصدر معتمد':data.cost} · قياس مشاهدة التسجيل: غير متاح من رابط المزود.</p><div className={styles.table}><table><thead><tr><th>المحاضرة</th><th>الموعد</th><th>المضيف</th><th>الحالة</th><th>المطلوب حضورهم</th></tr></thead><tbody>{(data.rows||[]).map((r,i)=><tr key={i}><td>{r.title}</td><td>{date(r.starts_at)}</td><td>{r.host_name}</td><td>{states[r.state]||r.state}</td><td>{r.expected_learners}</td></tr>)}</tbody></table></div>{permissions.export&&<button disabled={busy} onClick={async()=>{try{const response=await fetch('/api/zoom/export',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tenantSlug:slug,payload:options}),cache:'no-store'});if(!response.ok)throw Error('تعذر تصدير التقرير.');const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download='odeir-zoom-report.csv';a.click();URL.revokeObjectURL(url);}catch(e){setError(e.message);}}}>تصدير الصفحة الحالية CSV</button>}</>}
  {!compact&&<div className={styles.actions}><button disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-50))}>السابق</button><span>الصفحة {offset/50+1}</span><button disabled={Math.max(data.sessions?.length||0,data.hosts?.length||0,data.rows?.length||0,data.recordings?.length||0)<50} onClick={()=>setOffset(offset+50)}>التالي</button></div>}
  </>}
 </section>;
}
function RecordingList({rows,canPublish,busy,action}){return <section><h2>التسجيلات</h2>{!rows.length&&<Empty>لا توجد تسجيلات متاحة. ظهور التسجيل يعتمد على المعالجة والترخيص لدى زووم.</Empty>}<div className={styles.cards}>{rows.map(r=><article className={styles.card} key={r.id}><h3>{r.title}</h3><p>{r.file_type} · {states[r.state]||r.state} · {Math.round(r.size_bytes/1024/1024)} MB</p><small>انتهاء الإتاحة: {date(r.expires_at)}</small><div className={styles.actions}><button disabled={busy} onClick={async()=>{const result=await action('recording_access',{recordingId:r.id});if(result?.url)window.location.assign(result.url);}}>مراجعة التسجيل</button>{canPublish&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);action(r.state==='published'?'withdraw_recording':'publish_recording',{recordingId:r.id,reviewed:f.get('reviewed')==='on',reason:f.get('reason')});}}><label><input type="checkbox" name="reviewed" required/> راجعت محتوى التسجيل وصلاحية نشره.</label><Field label="سبب القرار"><input name="reason" required minLength={5}/></Field><button disabled={busy}>{r.state==='published'?'إيقاف الإتاحة':'نشر التسجيل'}</button></form>}</div></article>)}</div></section>;}
function AttendanceReview({details,busy,action}){return <section className={styles.card}><h2>أدلة حضور {details.row.title}</h2><p>المراجعة تُحدّث سجل حضور أودير القائم. نقص الأدلة يبقى ظاهرًا.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);action('teaching_window',{linkId:details.row.linkId,startsAt:asDate(f.get('from')),endsAt:asDate(f.get('to')),reason:f.get('reason'),breaks:[]});}}><div className={styles.fields}><Field label="بداية نافذة التعليم"><input name="from" type="datetime-local" required defaultValue={local(details.row.startsAt)}/></Field><Field label="نهاية نافذة التعليم"><input name="to" type="datetime-local" required defaultValue={local(details.row.endsAt)}/></Field><Field label="سبب اعتماد النافذة"><input name="reason" required minLength={5}/></Field></div><button disabled={busy}>اعتماد نافذة التعليم</button></form>{(details.data.roster||[]).map(r=><form key={r.enrollment_id} className={styles.row} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);action('approve_attendance',{linkId:details.row.linkId,enrollmentId:r.enrollment_id,reason:f.get('reason')});}}><b>{r.full_name}</b><span>{r.evidence.percent==null?'لا مقام معتمد':`${Number(r.evidence.percent).toFixed(1)}٪`} · {r.evidence.quality==='complete'?'أدلة مكتملة':'تحتاج مراجعة'}</span><input name="reason" aria-label={`سبب اعتماد حضور ${r.full_name}`} required minLength={5} placeholder="سبب الاعتماد"/><button disabled={busy||r.evidence.quality!=='complete'}>اعتماد النتيجة</button></form>)}{details.data.unmatched?.length>0&&<p role="status">توجد {details.data.unmatched.length} فترة حضور تحتاج مطابقة هوية أو استكمال دليل قبل الاعتماد.</p>}</section>;}
