// Run in a disposable checkout: only synthetic data and loopback HTTP are used.
import {spawn} from 'node:child_process';import {writeFile,mkdir,readFile,rm} from 'node:fs/promises';import {createRequire}from'node:module';import assert from'node:assert/strict';import {setTimeout as delay}from'node:timers/promises';
const require=createRequire(process.env.ZOOM_PLAYWRIGHT_PACKAGE||`${process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES}/playwright/package.json`);const{chromium}=require('playwright');
const origin='http://127.0.0.1:47898';const fixture='http://127.0.0.1:47899';const children=[];const logs=[];let browser;const evidence={runtime:'Chromium + Next dev + real migration SQL via PGlite',provider:'Synthetic adapter; no live Zoom/messaging/AI',auth:'Synthetic local JWT seam; SQL authorization and canonical financial functions execute',checks:[],blockedExternal:[],consoleErrors:[],expectedResourceErrors:[]};
const env={...process.env,ZOOM_UI_FIXTURE:'true',NEXT_PUBLIC_SUPABASE_URL:fixture,NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:'synthetic-anon',SUPABASE_URL:fixture};
function start(args){const child=spawn(process.execPath,args,{env,stdio:['ignore','pipe','pipe']});children.push(child);child.stdout.on('data',s=>logs.push(String(s)));child.stderr.on('data',s=>logs.push(String(s)));return child;}
async function ready(url){for(let i=0;i<300;i++){try{if((await fetch(url)).ok)return;}catch{}await delay(200);}throw Error(`Not ready: ${url}\n${logs.join('').slice(-3000)}`);}
async function post(page,action,payload){return page.evaluate(async({action,payload})=>{const r=await fetch(`/api/zoom/${action}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tenantSlug:'marktone',commandId:crypto.randomUUID(),payload})});return{status:r.status,body:await r.json()};},{action,payload});}
try{
 start(['scripts/zoom-ui-fixture.mjs']);await ready(fixture+'/health');const tokens=await(await fetch(fixture+'/fixture')).json();
 start(['node_modules/next/dist/bin/next','dev','--hostname','127.0.0.1','--port','47898']);await ready(origin+'/zoom-validation-fixture');
 browser=await chromium.launch({executablePath:process.env.ZOOM_CHROMIUM_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--no-zygote'],headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'ar-SA'});await context.route('**/*',route=>{const url=route.request().url();if(new URL(url).hostname==='127.0.0.1')return route.continue();evidence.blockedExternal.push(new URL(url).hostname);return route.abort();});
 await context.addCookies([{name:'mt_access',value:tokens.admin,url:origin}]);const page=await context.newPage();page.on('pageerror',error=>evidence.consoleErrors.push(error.message));page.on('console',message=>{if(message.type()==='error'){const url=message.location().url||'';const expected=url.startsWith('https://fonts.googleapis.com/')||(/\/api\/zoom\/(instructor_start|export)$/.test(url)||url.includes('/api/zoom/reports/'));(expected?evidence.expectedResourceErrors:evidence.consoleErrors).push({text:message.text(),url});}});
 await page.goto(origin+'/zoom-validation-fixture');await page.getByRole('heading',{name:'تشغيل زووم',exact:true}).waitFor();await page.getByRole('heading',{name:'التواصل الفعال مع المتدربين',exact:true}).waitFor();
 assert.equal(await page.getByText('Runtime Error',{exact:true}).count(),0);evidence.checks.push('Real Arabic account/session snapshot loaded, no runtime overlay');
 await mkdir('docs/zoom/evidence',{recursive:true});await writeFile('docs/zoom/evidence/ui-initial.txt',await page.locator('body').innerText());await page.screenshot({path:'docs/zoom/evidence/ui-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'الحسابات والمضيفون',exact:true}).click();await page.getByRole('heading',{name:'حساب الاختبار الاصطناعي'}).waitFor();await page.getByRole('heading',{name:'المضيف الاختباري'}).waitFor();evidence.checks.push('Account/host controls render actual SQL data');
 await page.getByRole('button',{name:'المحاضرات',exact:true}).click();await page.getByRole('button',{name:'توزيع المحاضرة',exact:true}).click();
 const form=page.locator('form').filter({has:page.getByRole('heading',{name:'ورشة التطبيقات العملية',exact:true})});await form.locator('select[name=instructorId]').selectOption({index:1});
 await form.getByRole('button',{name:'فحص الموارد',exact:true}).click();await page.getByText(/الموارد المؤهلة الآن: 1/).waitFor();await form.getByRole('button',{name:'حجز وإنشاء',exact:true}).click();await page.getByRole('status').filter({hasText:'تم حفظ الطلب'}).waitFor();
 const dispatch=await(await fetch(fixture+'/fixture/dispatch',{method:'POST'})).json();evidence.dispatch=dispatch;await page.getByRole('button',{name:'تحديث الحالة',exact:true}).click();
 await page.locator('article').filter({has:page.getByRole('heading',{name:'ورشة التطبيقات العملية',exact:true})}).getByRole('button',{name:'تعديل أو معالجة',exact:true}).waitFor();
 await page.locator('article').filter({has:page.getByRole('heading',{name:'ورشة التطبيقات العملية',exact:true})}).getByText(/جاهزة/).waitFor();await page.waitForFunction(()=>![...document.querySelectorAll('button')].find(b=>b.textContent==='تحديث الحالة')?.disabled);
 const sql=await(await fetch(fixture+'/fixture/evidence')).json();assert.ok(sql.links.some(l=>l.meeting_id==='77777777701'&&l.state==='ready'));assert.equal(sql.reservations,1);evidence.sql=sql;evidence.checks.push('UI assignment -> Next API -> real SQL reservation -> edge dispatch -> provider adapter -> SQL ready');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'docs/zoom/evidence/ui-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.keyboard.press('Tab');assert.ok(await page.evaluate(()=>document.activeElement!==document.body));evidence.checks.push('390px mobile has no document overflow; keyboard Tab reaches actionable control');for(const width of [360,768]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}evidence.checks.push('360px mobile and 768px tablet have no document overflow');await page.setViewportSize({width:390,height:844});
 await page.getByRole('button',{name:'التقارير',exact:true}).click();await page.getByRole('heading',{name:'التشغيل في الفترة المحددة'}).waitFor();const exported=await page.evaluate(async()=>{const r=await fetch('/api/zoom/export',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tenantSlug:'marktone',payload:{}})});return{status:r.status,type:r.headers.get('content-type'),body:await r.text()};});assert.equal(exported.status,200);assert.match(exported.type,/text\/csv/);evidence.checks.push('Report and server-authorized CSV export work');
 const report=await post(page,'report_request',{});assert.equal(report.status,200);await fetch(fixture+'/fixture/dispatch',{method:'POST'});const reportTicket=await post(page,'report_ticket',{exportId:report.body.id});assert.equal(reportTicket.status,200);const reportFile=await page.evaluate(async path=>{const r=await fetch(path);return{status:r.status,body:await r.text()};},reportTicket.body.path);assert.equal(reportFile.status,200);assert.ok(reportFile.body.includes('التواصل الفعال'));evidence.checks.push('Background report request -> real worker -> owner ticket -> streamed CSV succeeds');

 await context.clearCookies();await context.addCookies([{name:'mt_access',value:tokens.learner,url:origin}]);const rejected=await post(page,'instructor_start',{sessionId:tokens.session,asHost:true,role:1});assert.ok(rejected.status>=400);assert.doesNotMatch(JSON.stringify(rejected.body),/zak=|start_url/);evidence.checks.push('Learner role/asHost tampering denied by SQL with no host URL');
 const deniedExport=await post(page,'export',{});assert.ok(deniedExport.status>=400);evidence.checks.push('Learner cannot export staff reports');const copiedReport=await page.evaluate(async path=>(await fetch(path)).status,reportTicket.body.path);assert.equal(copiedReport,403);evidence.checks.push('Copied staff report URL is denied to learner');
 await page.goto(`${origin}/training/marktone/sessions/${tokens.session}`);await page.getByRole('button',{name:/دخول/}).first().waitFor();await page.screenshot({path:'docs/zoom/evidence/ui-learner.png',fullPage:true});evidence.checks.push('Standalone authorized learner lecture page renders without LMS activation');
 assert.deepEqual(evidence.consoleErrors,[]);evidence.status='passed';console.log('Zoom UI and HTTP/SQL verification passed');
}catch(error){evidence.status='failed';evidence.error=error.message;process.exitCode=1;console.error(error.message);}finally{
 await browser?.close();for(const child of children.reverse())child.kill('SIGTERM');await delay(300);await writeFile('/tmp/odeir-zoom-ui-servers.log',logs.join(''));await mkdir('docs/zoom/evidence',{recursive:true});await writeFile('docs/zoom/evidence/ui-http-sql.json',JSON.stringify(evidence,null,2)+'\n');
 // Remove only the explicitly generated verification page, never application data.
 const path='app/zoom-validation-fixture/page.jsx';try{if((await readFile(path,'utf8')).includes('ZOOM_UI_FIXTURE'))await rm('app/zoom-validation-fixture',{recursive:true});}catch{}
}
