begin;

-- Paymob readiness evidence is generated by trusted database functions. Its
-- canonical metadata names (for example "credentials" and
-- "credentialVersionId") intentionally contain words that the generic public
-- JSON secret-key scanner rejects. Keep that scanner unchanged for every other
-- payment provider and validate Paymob against this closed, typed schema.
create or replace function private_app.paymob_readiness_evidence_safe_v1(
  p_value jsonb
)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select coalesce(
    pg_catalog.jsonb_typeof(p_value) = 'object'
    and not exists (
      select 1
      from pg_catalog.jsonb_each(p_value) as entry(check_key, evidence)
      where entry.check_key not in (
          'credentials',
          'intention_create',
          'webhook_hmac',
          'paid_transaction',
          'duplicate_delivery',
          'failed_transaction',
          'transaction_inquiry',
          'credential_rotation_callback',
          'refund_inquiry',
          'refund_initiation',
          'live_credentials',
          'live_card_integration_callback',
          'edge_query_redaction_waf',
          'reconciler_schedule',
          'outbox_delivery'
        )
        or pg_catalog.jsonb_typeof(entry.evidence) <> 'object'
        or exists (
          select 1
          from pg_catalog.jsonb_object_keys(entry.evidence) as member(field_name)
          where member.field_name not in (
            'passed',
            'environment',
            'checkedAt',
            'credentialVersionId',
            'evidenceSha256',
            'sourceType',
            'sourceId',
            'errorCode'
          )
        )
        or not (entry.evidence ? 'passed')
        or pg_catalog.jsonb_typeof(entry.evidence -> 'passed') <> 'boolean'
        or not (entry.evidence ? 'environment')
        or pg_catalog.jsonb_typeof(entry.evidence -> 'environment') <> 'string'
        or entry.evidence ->> 'environment' not in ('sandbox', 'live')
        or not (entry.evidence ? 'checkedAt')
        or pg_catalog.jsonb_typeof(entry.evidence -> 'checkedAt') <> 'string'
        or entry.evidence ->> 'checkedAt'
          !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]+)?(Z|[+-][0-9]{2}:[0-9]{2})$'
        or (
          entry.evidence ? 'credentialVersionId'
          and (
            pg_catalog.jsonb_typeof(
              entry.evidence -> 'credentialVersionId'
            ) <> 'string'
            or entry.evidence ->> 'credentialVersionId'
              !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
          )
        )
        or (
          entry.evidence ? 'evidenceSha256'
          and (
            pg_catalog.jsonb_typeof(
              entry.evidence -> 'evidenceSha256'
            ) <> 'string'
            or entry.evidence ->> 'evidenceSha256' !~ '^[a-f0-9]{64}$'
          )
        )
        or (
          entry.evidence ? 'sourceType'
          and (
            pg_catalog.jsonb_typeof(entry.evidence -> 'sourceType') <> 'string'
            or entry.evidence ->> 'sourceType' not in (
              'credential_version',
              'payment_attempt',
              'webhook_delivery',
              'reconciliation',
              'operational_attestation'
            )
          )
        )
        or (
          entry.evidence ? 'sourceId'
          and (
            pg_catalog.jsonb_typeof(entry.evidence -> 'sourceId') <> 'string'
            or entry.evidence ->> 'sourceId'
              !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
          )
        )
        or (
          entry.evidence ? 'errorCode'
          and (
            pg_catalog.jsonb_typeof(entry.evidence -> 'errorCode') <> 'string'
            or entry.evidence ->> 'errorCode'
              !~ '^[a-z][a-z0-9_]{1,80}$'
          )
        )
    ),
    false
  )
$$;

revoke all on function private_app.paymob_readiness_evidence_safe_v1(jsonb)
from public, anon, authenticated, service_role;

comment on function private_app.paymob_readiness_evidence_safe_v1(jsonb)
is 'Accepts only the bounded, typed, non-secret Paymob readiness evidence schema.';

alter table marketplace.payment_provider_configs
  drop constraint if exists payment_provider_readiness_object_check_v1;

alter table marketplace.payment_provider_configs
  add constraint payment_provider_readiness_object_check_v1
  check (
    pg_catalog.jsonb_typeof(readiness_evidence) = 'object'
    and case
      when provider_key = 'paymob'
        then private_app.paymob_readiness_evidence_safe_v1(
          readiness_evidence
        )
      else not private_app.jsonb_has_sensitive_key(readiness_evidence)
    end
  ) not valid;

alter table marketplace.payment_provider_configs
  validate constraint payment_provider_readiness_object_check_v1;

commit;
