-- Read-only backend deployment preflight. No operational tenant rows or secrets.
-- Target verified out of band: gswpbwdactcstkasddta; snapshot source 5ae904735d42249f7214770303cc9ab25bae75fa.
select jsonb_build_object(
 'zoom_schema_present',to_regnamespace('zoom_core') is not null,
 'zoom_snapshot_present',to_regprocedure('public.v1_zoom_snapshot(text,text,jsonb)') is not null,
 'missing_relations',(select coalesce(jsonb_agg(name),'[]') from unnest(array['academy.assessment_results','academy.attendance_records','academy.certificates','academy.course_authoring','academy.course_authoring_releases','academy.course_run_rules','academy.course_run_sessions','academy.course_runs','academy.courses','academy.enrollments','academy.platform_memberships','academy.students','academy.training_automation_jobs','academy.training_automation_settings','academy.training_course_versions','academy.training_invitations','academy.training_learner_accounts','academy.training_learning_events','academy.training_run_instructors','academy.training_units','access_control.membership_roles','access_control.memberships','access_control.permissions','access_control.role_permissions','access_control.roles','access_control.subjects','auth.users','core.branches','core.odeiry_messages','core.odeiry_runs','core.odeiry_usage_events','core.tenants','marketing_hub.campaigns','people.staff_profiles','sales_core.activities','sales_core.contact_identities','sales_core.contacts','vault.decrypted_secrets','vault.secrets']) d(name) where to_regclass(name) is null),
 'missing_functions',(select coalesce(jsonb_agg(name),'[]') from unnest(array['auth.uid','private_app.academy_has_permission_v1','private_app.academy_platform_enabled_v1','private_app.can_view_tenant_team','private_app.current_staff_id','private_app.current_subject_id','private_app.find_contact_by_identity','private_app.has_tenant_permission','private_app.normalize_lead_phone','private_app.normalize_training_phone','private_app.sales_followup_contact','private_app.tenant_addon_enabled','private_app.training_is_instructor_v1','private_app.training_is_learner_v1','private_app.training_journey_financial_access_v1','private_app.write_audit','public.v1_academy_authoring_action','public.v2_tenant_create_contact','vault.create_secret','vault.update_secret']) d(name) where not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname=split_part(d.name,'.',1) and p.proname=split_part(d.name,'.',2)))
) as preflight;
-- Existence is necessary, not sufficient: this is not a signature/schema parity, restore, or acceptance proof.
